/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    unit?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    zipcode?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    state?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    longitude?: string;
    /**
     * 
     * @type {string}
     * @memberof Address
     */
    lattitude?: string;
}

/**
 * Check if a given object implements the Address interface.
 */
export function instanceOfAddress(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AddressFromJSON(json: any): Address {
    return AddressFromJSONTyped(json, false);
}

export function AddressFromJSONTyped(json: any, ignoreDiscriminator: boolean): Address {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'zipcode': !exists(json, 'zipcode') ? undefined : json['zipcode'],
        'city': !exists(json, 'city') ? undefined : json['city'],
        'state': !exists(json, 'state') ? undefined : json['state'],
        'longitude': !exists(json, 'longitude') ? undefined : json['longitude'],
        'lattitude': !exists(json, 'lattitude') ? undefined : json['lattitude'],
    };
}

export function AddressToJSON(value?: Address | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'address': value.address,
        'unit': value.unit,
        'zipcode': value.zipcode,
        'city': value.city,
        'state': value.state,
        'longitude': value.longitude,
        'lattitude': value.lattitude,
    };
}

