/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlaidAccountRecurringTransaction } from './PlaidAccountRecurringTransaction';
import {
    PlaidAccountRecurringTransactionFromJSON,
    PlaidAccountRecurringTransactionFromJSONTyped,
    PlaidAccountRecurringTransactionToJSON,
} from './PlaidAccountRecurringTransaction';

/**
 * 
 * @export
 * @interface BulkUpdateRecurringTransactionResponse
 */
export interface BulkUpdateRecurringTransactionResponse {
    /**
     * 
     * @type {Array<PlaidAccountRecurringTransaction>}
     * @memberof BulkUpdateRecurringTransactionResponse
     */
    transactions?: Array<PlaidAccountRecurringTransaction>;
}

/**
 * Check if a given object implements the BulkUpdateRecurringTransactionResponse interface.
 */
export function instanceOfBulkUpdateRecurringTransactionResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BulkUpdateRecurringTransactionResponseFromJSON(json: any): BulkUpdateRecurringTransactionResponse {
    return BulkUpdateRecurringTransactionResponseFromJSONTyped(json, false);
}

export function BulkUpdateRecurringTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BulkUpdateRecurringTransactionResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactions': !exists(json, 'transactions') ? undefined : ((json['transactions'] as Array<any>).map(PlaidAccountRecurringTransactionFromJSON)),
    };
}

export function BulkUpdateRecurringTransactionResponseToJSON(value?: BulkUpdateRecurringTransactionResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactions': value.transactions === undefined ? undefined : ((value.transactions as Array<any>).map(PlaidAccountRecurringTransactionToJSON)),
    };
}

