/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * - BUSINESS_ACTIONABLE_INSIGHT_TYPE_OPERATING_EXPENSES: Operating Expenses: Insights on managing day-to-day operational costs.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_CASH_FLOW_MANAGEMENT: Cash Flow Management: Insights into cash inflows and outflows.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_REVENUE_GROWTH: Revenue Growth: Strategies or opportunities to increase revenue.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_COST_REDUCTION: Cost Reduction: Identifying areas where expenses can be minimized.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_INVENTORY_MANAGEMENT: Inventory Management: Insights on optimizing inventory levels and costs.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_CAPITAL_ALLOCATION: Capital Allocation: Guidance on efficient allocation of financial resources.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_INVESTMENT_OPPORTUNITIES: Investment Opportunities: Identifying potential profitable investments.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_RISK_ASSESSMENT: Risk Assessment: Insights into potential risks and mitigation strategies.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_TAX_PLANNING: Tax Planning: Suggestions for tax optimization.
 *  - BUSINESS_ACTIONABLE_INSIGHT_TYPE_DEBT_MANAGEMENT: Debt Management: Strategies for managing and reducing debt.
 * @export
 */
export const BusinessActionableInsightType = {
    Unspecified: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_UNSPECIFIED',
    OperatingExpenses: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_OPERATING_EXPENSES',
    CashFlowManagement: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_CASH_FLOW_MANAGEMENT',
    RevenueGrowth: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_REVENUE_GROWTH',
    CostReduction: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_COST_REDUCTION',
    InventoryManagement: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_INVENTORY_MANAGEMENT',
    CapitalAllocation: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_CAPITAL_ALLOCATION',
    InvestmentOpportunities: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_INVESTMENT_OPPORTUNITIES',
    RiskAssessment: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_RISK_ASSESSMENT',
    TaxPlanning: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_TAX_PLANNING',
    DebtManagement: 'BUSINESS_ACTIONABLE_INSIGHT_TYPE_DEBT_MANAGEMENT'
} as const;
export type BusinessActionableInsightType = typeof BusinessActionableInsightType[keyof typeof BusinessActionableInsightType];


export function instanceOfBusinessActionableInsightType(value: any): boolean {
    return Object.values(BusinessActionableInsightType).includes(value);
}

export function BusinessActionableInsightTypeFromJSON(json: any): BusinessActionableInsightType {
    return BusinessActionableInsightTypeFromJSONTyped(json, false);
}

export function BusinessActionableInsightTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BusinessActionableInsightType {
    return json as BusinessActionableInsightType;
}

export function BusinessActionableInsightTypeToJSON(value?: BusinessActionableInsightType | null): any {
    return value as any;
}

