/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialUserProfileType } from './FinancialUserProfileType';
import {
    FinancialUserProfileTypeFromJSON,
    FinancialUserProfileTypeFromJSONTyped,
    FinancialUserProfileTypeToJSON,
} from './FinancialUserProfileType';

/**
 * CategoryMonthlyTransactionCount
 * This message is used to represent the monthly transaction count of a category.
 * @export
 * @interface CategoryMonthlyTransactionCount
 */
export interface CategoryMonthlyTransactionCount {
    /**
     * 
     * @type {number}
     * @memberof CategoryMonthlyTransactionCount
     */
    month?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryMonthlyTransactionCount
     */
    personalFinanceCategoryPrimary?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryMonthlyTransactionCount
     */
    transactionCount?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryMonthlyTransactionCount
     */
    userId?: string;
    /**
     * 
     * @type {FinancialUserProfileType}
     * @memberof CategoryMonthlyTransactionCount
     */
    profileType?: FinancialUserProfileType;
}

/**
 * Check if a given object implements the CategoryMonthlyTransactionCount interface.
 */
export function instanceOfCategoryMonthlyTransactionCount(value: object): boolean {
    return true;
}

export function CategoryMonthlyTransactionCountFromJSON(json: any): CategoryMonthlyTransactionCount {
    return CategoryMonthlyTransactionCountFromJSONTyped(json, false);
}

export function CategoryMonthlyTransactionCountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryMonthlyTransactionCount {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'] == null ? undefined : json['month'],
        'personalFinanceCategoryPrimary': json['personalFinanceCategoryPrimary'] == null ? undefined : json['personalFinanceCategoryPrimary'],
        'transactionCount': json['transactionCount'] == null ? undefined : json['transactionCount'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'profileType': json['profileType'] == null ? undefined : FinancialUserProfileTypeFromJSON(json['profileType']),
    };
}

export function CategoryMonthlyTransactionCountToJSON(value?: CategoryMonthlyTransactionCount | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'month': value['month'],
        'personalFinanceCategoryPrimary': value['personalFinanceCategoryPrimary'],
        'transactionCount': value['transactionCount'],
        'userId': value['userId'],
        'profileType': FinancialUserProfileTypeToJSON(value['profileType']),
    };
}

