/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FinancialUserProfileType } from './FinancialUserProfileType';
import {
    FinancialUserProfileTypeFromJSON,
    FinancialUserProfileTypeFromJSONTyped,
    FinancialUserProfileTypeToJSON,
} from './FinancialUserProfileType';

/**
 * CategoryMonthlyExpenditure represents the monthly expenditure of a category.
 * This message is used to represent the monthly expenditure of a category.
 * @export
 * @interface CategoryMonthlyExpenditure
 */
export interface CategoryMonthlyExpenditure {
    /**
     * 
     * @type {number}
     * @memberof CategoryMonthlyExpenditure
     */
    month?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryMonthlyExpenditure
     */
    personalFinanceCategoryPrimary?: string;
    /**
     * 
     * @type {number}
     * @memberof CategoryMonthlyExpenditure
     */
    totalSpending?: number;
    /**
     * 
     * @type {string}
     * @memberof CategoryMonthlyExpenditure
     */
    userId?: string;
    /**
     * 
     * @type {FinancialUserProfileType}
     * @memberof CategoryMonthlyExpenditure
     */
    profileType?: FinancialUserProfileType;
}

/**
 * Check if a given object implements the CategoryMonthlyExpenditure interface.
 */
export function instanceOfCategoryMonthlyExpenditure(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CategoryMonthlyExpenditureFromJSON(json: any): CategoryMonthlyExpenditure {
    return CategoryMonthlyExpenditureFromJSONTyped(json, false);
}

export function CategoryMonthlyExpenditureFromJSONTyped(json: any, ignoreDiscriminator: boolean): CategoryMonthlyExpenditure {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'month': !exists(json, 'month') ? undefined : json['month'],
        'personalFinanceCategoryPrimary': !exists(json, 'personalFinanceCategoryPrimary') ? undefined : json['personalFinanceCategoryPrimary'],
        'totalSpending': !exists(json, 'totalSpending') ? undefined : json['totalSpending'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'profileType': !exists(json, 'profileType') ? undefined : FinancialUserProfileTypeFromJSON(json['profileType']),
    };
}

export function CategoryMonthlyExpenditureToJSON(value?: CategoryMonthlyExpenditure | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'month': value.month,
        'personalFinanceCategoryPrimary': value.personalFinanceCategoryPrimary,
        'totalSpending': value.totalSpending,
        'userId': value.userId,
        'profileType': FinancialUserProfileTypeToJSON(value.profileType),
    };
}

