/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckEmailExistsResponse
 */
export interface CheckEmailExistsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CheckEmailExistsResponse
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the CheckEmailExistsResponse interface.
 */
export function instanceOfCheckEmailExistsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CheckEmailExistsResponseFromJSON(json: any): CheckEmailExistsResponse {
    return CheckEmailExistsResponseFromJSONTyped(json, false);
}

export function CheckEmailExistsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckEmailExistsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_exists': !exists(json, 'exists') ? undefined : json['exists'],
    };
}

export function CheckEmailExistsResponseToJSON(value?: CheckEmailExistsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'exists': value._exists,
    };
}

