/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckIfQuotaExceededResponse
 */
export interface CheckIfQuotaExceededResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CheckIfQuotaExceededResponse
     */
    exceeded?: boolean;
}

/**
 * Check if a given object implements the CheckIfQuotaExceededResponse interface.
 */
export function instanceOfCheckIfQuotaExceededResponse(value: object): boolean {
    return true;
}

export function CheckIfQuotaExceededResponseFromJSON(json: any): CheckIfQuotaExceededResponse {
    return CheckIfQuotaExceededResponseFromJSONTyped(json, false);
}

export function CheckIfQuotaExceededResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckIfQuotaExceededResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'exceeded': json['exceeded'] == null ? undefined : json['exceeded'],
    };
}

export function CheckIfQuotaExceededResponseToJSON(value?: CheckIfQuotaExceededResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exceeded': value['exceeded'],
    };
}

