/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckUsernameExistsV2Response
 */
export interface CheckUsernameExistsV2Response {
    /**
     * 
     * @type {boolean}
     * @memberof CheckUsernameExistsV2Response
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the CheckUsernameExistsV2Response interface.
 */
export function instanceOfCheckUsernameExistsV2Response(value: object): boolean {
    return true;
}

export function CheckUsernameExistsV2ResponseFromJSON(json: any): CheckUsernameExistsV2Response {
    return CheckUsernameExistsV2ResponseFromJSONTyped(json, false);
}

export function CheckUsernameExistsV2ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckUsernameExistsV2Response {
    if (json == null) {
        return json;
    }
    return {
        
        '_exists': json['exists'] == null ? undefined : json['exists'],
    };
}

export function CheckUsernameExistsV2ResponseToJSON(value?: CheckUsernameExistsV2Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exists': value['_exists'],
    };
}

