/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CheckUsernameExistsResponse
 */
export interface CheckUsernameExistsResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CheckUsernameExistsResponse
     */
    _exists?: boolean;
}

/**
 * Check if a given object implements the CheckUsernameExistsResponse interface.
 */
export function instanceOfCheckUsernameExistsResponse(value: object): boolean {
    return true;
}

export function CheckUsernameExistsResponseFromJSON(json: any): CheckUsernameExistsResponse {
    return CheckUsernameExistsResponseFromJSONTyped(json, false);
}

export function CheckUsernameExistsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CheckUsernameExistsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        '_exists': json['exists'] == null ? undefined : json['exists'],
    };
}

export function CheckUsernameExistsResponseToJSON(value?: CheckUsernameExistsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'exists': value['_exists'],
    };
}

