/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response from creating a Markdown file.
 * @export
 * @interface CreateMarkdownFileResponse
 */
export interface CreateMarkdownFileResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateMarkdownFileResponse
     */
    fileId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateMarkdownFileResponse
     */
    fileUrl?: string;
}

/**
 * Check if a given object implements the CreateMarkdownFileResponse interface.
 */
export function instanceOfCreateMarkdownFileResponse(value: object): boolean {
    return true;
}

export function CreateMarkdownFileResponseFromJSON(json: any): CreateMarkdownFileResponse {
    return CreateMarkdownFileResponseFromJSONTyped(json, false);
}

export function CreateMarkdownFileResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMarkdownFileResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['fileId'] == null ? undefined : json['fileId'],
        'fileUrl': json['fileUrl'] == null ? undefined : json['fileUrl'],
    };
}

export function CreateMarkdownFileResponseToJSON(value?: CreateMarkdownFileResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'fileId': value['fileId'],
        'fileUrl': value['fileUrl'],
    };
}

