/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateManualLinkResponse
 */
export interface CreateManualLinkResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateManualLinkResponse
     */
    linkId?: string;
}

/**
 * Check if a given object implements the CreateManualLinkResponse interface.
 */
export function instanceOfCreateManualLinkResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateManualLinkResponseFromJSON(json: any): CreateManualLinkResponse {
    return CreateManualLinkResponseFromJSONTyped(json, false);
}

export function CreateManualLinkResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateManualLinkResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'linkId': !exists(json, 'linkId') ? undefined : json['linkId'],
    };
}

export function CreateManualLinkResponseToJSON(value?: CreateManualLinkResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'linkId': value.linkId,
    };
}

