/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
} from './Role';

/**
 * 
 * @export
 * @interface CreateRoleResponse
 */
export interface CreateRoleResponse {
    /**
     * 
     * @type {Role}
     * @memberof CreateRoleResponse
     */
    role?: Role;
}

/**
 * Check if a given object implements the CreateRoleResponse interface.
 */
export function instanceOfCreateRoleResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreateRoleResponseFromJSON(json: any): CreateRoleResponse {
    return CreateRoleResponseFromJSONTyped(json, false);
}

export function CreateRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRoleResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'role': !exists(json, 'role') ? undefined : RoleFromJSON(json['role']),
    };
}

export function CreateRoleResponseToJSON(value?: CreateRoleResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'role': RoleToJSON(value.role),
    };
}

