/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Workspace } from './Workspace';
import {
    WorkspaceFromJSON,
    WorkspaceFromJSONTyped,
    WorkspaceToJSON,
} from './Workspace';

/**
 * 
 * @export
 * @interface CreateWorkspaceResponse
 */
export interface CreateWorkspaceResponse {
    /**
     * 
     * @type {Workspace}
     * @memberof CreateWorkspaceResponse
     */
    workspace?: Workspace;
}

/**
 * Check if a given object implements the CreateWorkspaceResponse interface.
 */
export function instanceOfCreateWorkspaceResponse(value: object): boolean {
    return true;
}

export function CreateWorkspaceResponseFromJSON(json: any): CreateWorkspaceResponse {
    return CreateWorkspaceResponseFromJSONTyped(json, false);
}

export function CreateWorkspaceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateWorkspaceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workspace': json['workspace'] == null ? undefined : WorkspaceFromJSON(json['workspace']),
    };
}

export function CreateWorkspaceResponseToJSON(value?: CreateWorkspaceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'workspace': WorkspaceToJSON(value['workspace']),
    };
}

