/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * CreditNoteLineItem is used to represent a credit note's line items.
 * @export
 * @interface CreditNoteLineItem
 */
export interface CreditNoteLineItem {
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    quantity?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    unitPrice?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    taxRate?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    totalLineAmount?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    trackingCategory?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreditNoteLineItem
     */
    trackingCategories?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    remoteId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    item?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreditNoteLineItem
     */
    remoteWasDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CreditNoteLineItem
     */
    memo?: string;
}

/**
 * Check if a given object implements the CreditNoteLineItem interface.
 */
export function instanceOfCreditNoteLineItem(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CreditNoteLineItemFromJSON(json: any): CreditNoteLineItem {
    return CreditNoteLineItemFromJSONTyped(json, false);
}

export function CreditNoteLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditNoteLineItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'quantity': !exists(json, 'quantity') ? undefined : json['quantity'],
        'unitPrice': !exists(json, 'unitPrice') ? undefined : json['unitPrice'],
        'taxRate': !exists(json, 'taxRate') ? undefined : json['taxRate'],
        'totalLineAmount': !exists(json, 'totalLineAmount') ? undefined : json['totalLineAmount'],
        'trackingCategory': !exists(json, 'trackingCategory') ? undefined : json['trackingCategory'],
        'trackingCategories': !exists(json, 'trackingCategories') ? undefined : json['trackingCategories'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'remoteId': !exists(json, 'remoteId') ? undefined : json['remoteId'],
        'item': !exists(json, 'item') ? undefined : json['item'],
        'remoteWasDeleted': !exists(json, 'remoteWasDeleted') ? undefined : json['remoteWasDeleted'],
        'memo': !exists(json, 'memo') ? undefined : json['memo'],
    };
}

export function CreditNoteLineItemToJSON(value?: CreditNoteLineItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'quantity': value.quantity,
        'unitPrice': value.unitPrice,
        'taxRate': value.taxRate,
        'totalLineAmount': value.totalLineAmount,
        'trackingCategory': value.trackingCategory,
        'trackingCategories': value.trackingCategories,
        'account': value.account,
        'company': value.company,
        'remoteId': value.remoteId,
        'item': value.item,
        'remoteWasDeleted': value.remoteWasDeleted,
        'memo': value.memo,
    };
}

