/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountStatements } from './AccountStatements';
import {
    AccountStatementsFromJSON,
    AccountStatementsFromJSONTyped,
    AccountStatementsToJSON,
} from './AccountStatements';
import type { Apr } from './Apr';
import {
    AprFromJSON,
    AprFromJSONTyped,
    AprToJSON,
} from './Apr';
import type { BankAccountStatus } from './BankAccountStatus';
import {
    BankAccountStatusFromJSON,
    BankAccountStatusFromJSONTyped,
    BankAccountStatusToJSON,
} from './BankAccountStatus';
import type { PlaidAccountRecurringTransaction } from './PlaidAccountRecurringTransaction';
import {
    PlaidAccountRecurringTransactionFromJSON,
    PlaidAccountRecurringTransactionFromJSONTyped,
    PlaidAccountRecurringTransactionToJSON,
} from './PlaidAccountRecurringTransaction';
import type { PlaidAccountTransaction } from './PlaidAccountTransaction';
import {
    PlaidAccountTransactionFromJSON,
    PlaidAccountTransactionFromJSONTyped,
    PlaidAccountTransactionToJSON,
} from './PlaidAccountTransaction';
import type { Pocket } from './Pocket';
import {
    PocketFromJSON,
    PocketFromJSONTyped,
    PocketToJSON,
} from './Pocket';

/**
 * 
 * @export
 * @interface CreditAccount
 */
export interface CreditAccount {
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    number?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditAccount
     */
    balance?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditAccount
     */
    currentFunds?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    balanceLimit?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    plaidAccountId?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    subtype?: string;
    /**
     * 
     * @type {boolean}
     * @memberof CreditAccount
     */
    isOverdue?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CreditAccount
     */
    lastPaymentAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    lastPaymentDate?: string;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    lastStatementIssueDate?: string;
    /**
     * 
     * @type {number}
     * @memberof CreditAccount
     */
    minimumAmountDueDate?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    nextPaymentDate?: string;
    /**
     * 
     * @type {Array<Apr>}
     * @memberof CreditAccount
     */
    aprs?: Array<Apr>;
    /**
     * 
     * @type {number}
     * @memberof CreditAccount
     */
    lastStatementBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof CreditAccount
     */
    minimumPaymentAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof CreditAccount
     */
    nextPaymentDueDate?: string;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof CreditAccount
     */
    status?: BankAccountStatus;
    /**
     * 
     * @type {Array<PlaidAccountTransaction>}
     * @memberof CreditAccount
     */
    transactions?: Array<PlaidAccountTransaction>;
    /**
     * 
     * @type {Array<PlaidAccountRecurringTransaction>}
     * @memberof CreditAccount
     */
    recurringTransactions?: Array<PlaidAccountRecurringTransaction>;
    /**
     * 
     * @type {Array<Pocket>}
     * @memberof CreditAccount
     */
    pockets?: Array<Pocket>;
    /**
     * 
     * @type {Array<AccountStatements>}
     * @memberof CreditAccount
     */
    statements?: Array<AccountStatements>;
}

/**
 * Check if a given object implements the CreditAccount interface.
 */
export function instanceOfCreditAccount(value: object): boolean {
    return true;
}

export function CreditAccountFromJSON(json: any): CreditAccount {
    return CreditAccountFromJSONTyped(json, false);
}

export function CreditAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreditAccount {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'name': json['name'] == null ? undefined : json['name'],
        'number': json['number'] == null ? undefined : json['number'],
        'type': json['type'] == null ? undefined : json['type'],
        'balance': json['balance'] == null ? undefined : json['balance'],
        'currentFunds': json['currentFunds'] == null ? undefined : json['currentFunds'],
        'balanceLimit': json['balanceLimit'] == null ? undefined : json['balanceLimit'],
        'plaidAccountId': json['plaidAccountId'] == null ? undefined : json['plaidAccountId'],
        'subtype': json['subtype'] == null ? undefined : json['subtype'],
        'isOverdue': json['isOverdue'] == null ? undefined : json['isOverdue'],
        'lastPaymentAmount': json['lastPaymentAmount'] == null ? undefined : json['lastPaymentAmount'],
        'lastPaymentDate': json['lastPaymentDate'] == null ? undefined : json['lastPaymentDate'],
        'lastStatementIssueDate': json['lastStatementIssueDate'] == null ? undefined : json['lastStatementIssueDate'],
        'minimumAmountDueDate': json['minimumAmountDueDate'] == null ? undefined : json['minimumAmountDueDate'],
        'nextPaymentDate': json['nextPaymentDate'] == null ? undefined : json['nextPaymentDate'],
        'aprs': json['aprs'] == null ? undefined : ((json['aprs'] as Array<any>).map(AprFromJSON)),
        'lastStatementBalance': json['lastStatementBalance'] == null ? undefined : json['lastStatementBalance'],
        'minimumPaymentAmount': json['minimumPaymentAmount'] == null ? undefined : json['minimumPaymentAmount'],
        'nextPaymentDueDate': json['nextPaymentDueDate'] == null ? undefined : json['nextPaymentDueDate'],
        'status': json['status'] == null ? undefined : BankAccountStatusFromJSON(json['status']),
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(PlaidAccountTransactionFromJSON)),
        'recurringTransactions': json['recurringTransactions'] == null ? undefined : ((json['recurringTransactions'] as Array<any>).map(PlaidAccountRecurringTransactionFromJSON)),
        'pockets': json['pockets'] == null ? undefined : ((json['pockets'] as Array<any>).map(PocketFromJSON)),
        'statements': json['statements'] == null ? undefined : ((json['statements'] as Array<any>).map(AccountStatementsFromJSON)),
    };
}

export function CreditAccountToJSON(value?: CreditAccount | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'userId': value['userId'],
        'name': value['name'],
        'number': value['number'],
        'type': value['type'],
        'balance': value['balance'],
        'currentFunds': value['currentFunds'],
        'balanceLimit': value['balanceLimit'],
        'plaidAccountId': value['plaidAccountId'],
        'subtype': value['subtype'],
        'isOverdue': value['isOverdue'],
        'lastPaymentAmount': value['lastPaymentAmount'],
        'lastPaymentDate': value['lastPaymentDate'],
        'lastStatementIssueDate': value['lastStatementIssueDate'],
        'minimumAmountDueDate': value['minimumAmountDueDate'],
        'nextPaymentDate': value['nextPaymentDate'],
        'aprs': value['aprs'] == null ? undefined : ((value['aprs'] as Array<any>).map(AprToJSON)),
        'lastStatementBalance': value['lastStatementBalance'],
        'minimumPaymentAmount': value['minimumPaymentAmount'],
        'nextPaymentDueDate': value['nextPaymentDueDate'],
        'status': BankAccountStatusToJSON(value['status']),
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(PlaidAccountTransactionToJSON)),
        'recurringTransactions': value['recurringTransactions'] == null ? undefined : ((value['recurringTransactions'] as Array<any>).map(PlaidAccountRecurringTransactionToJSON)),
        'pockets': value['pockets'] == null ? undefined : ((value['pockets'] as Array<any>).map(PocketToJSON)),
        'statements': value['statements'] == null ? undefined : ((value['statements'] as Array<any>).map(AccountStatementsToJSON)),
    };
}

