/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteUserProfileResponse1
 */
export interface DeleteUserProfileResponse1 {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteUserProfileResponse1
     */
    profileDeleted?: boolean;
}

/**
 * Check if a given object implements the DeleteUserProfileResponse1 interface.
 */
export function instanceOfDeleteUserProfileResponse1(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function DeleteUserProfileResponse1FromJSON(json: any): DeleteUserProfileResponse1 {
    return DeleteUserProfileResponse1FromJSONTyped(json, false);
}

export function DeleteUserProfileResponse1FromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteUserProfileResponse1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profileDeleted': !exists(json, 'profileDeleted') ? undefined : json['profileDeleted'],
    };
}

export function DeleteUserProfileResponse1ToJSON(value?: DeleteUserProfileResponse1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profileDeleted': value.profileDeleted,
    };
}

