/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditPostResponse
 */
export interface EditPostResponse {
    /**
     * 
     * @type {boolean}
     * @memberof EditPostResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the EditPostResponse interface.
 */
export function instanceOfEditPostResponse(value: object): boolean {
    return true;
}

export function EditPostResponseFromJSON(json: any): EditPostResponse {
    return EditPostResponseFromJSONTyped(json, false);
}

export function EditPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
    };
}

export function EditPostResponseToJSON(value?: EditPostResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
    };
}

