/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialUserProfileType } from './FinancialUserProfileType';
import {
    FinancialUserProfileTypeFromJSON,
    FinancialUserProfileTypeFromJSONTyped,
    FinancialUserProfileTypeToJSON,
} from './FinancialUserProfileType';

/**
 * ExpenseMetricsFinancialSubProfileMetrics
 * This message is used to represent the financial sub profile metrics of a user.
 * @export
 * @interface ExpenseMetricsFinancialSubProfileMetrics
 */
export interface ExpenseMetricsFinancialSubProfileMetrics {
    /**
     * 
     * @type {number}
     * @memberof ExpenseMetricsFinancialSubProfileMetrics
     */
    month?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseMetricsFinancialSubProfileMetrics
     */
    spentLastWeek?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseMetricsFinancialSubProfileMetrics
     */
    spentLastMonth?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseMetricsFinancialSubProfileMetrics
     */
    spentLastSixMonths?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseMetricsFinancialSubProfileMetrics
     */
    averageMonthlyDiscretionarySpending?: number;
    /**
     * 
     * @type {number}
     * @memberof ExpenseMetricsFinancialSubProfileMetrics
     */
    averageMonthlyRecurringSpending?: number;
    /**
     * 
     * @type {string}
     * @memberof ExpenseMetricsFinancialSubProfileMetrics
     */
    userId?: string;
    /**
     * 
     * @type {FinancialUserProfileType}
     * @memberof ExpenseMetricsFinancialSubProfileMetrics
     */
    profileType?: FinancialUserProfileType;
}

/**
 * Check if a given object implements the ExpenseMetricsFinancialSubProfileMetrics interface.
 */
export function instanceOfExpenseMetricsFinancialSubProfileMetrics(value: object): boolean {
    return true;
}

export function ExpenseMetricsFinancialSubProfileMetricsFromJSON(json: any): ExpenseMetricsFinancialSubProfileMetrics {
    return ExpenseMetricsFinancialSubProfileMetricsFromJSONTyped(json, false);
}

export function ExpenseMetricsFinancialSubProfileMetricsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExpenseMetricsFinancialSubProfileMetrics {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'] == null ? undefined : json['month'],
        'spentLastWeek': json['spentLastWeek'] == null ? undefined : json['spentLastWeek'],
        'spentLastMonth': json['spentLastMonth'] == null ? undefined : json['spentLastMonth'],
        'spentLastSixMonths': json['spentLastSixMonths'] == null ? undefined : json['spentLastSixMonths'],
        'averageMonthlyDiscretionarySpending': json['averageMonthlyDiscretionarySpending'] == null ? undefined : json['averageMonthlyDiscretionarySpending'],
        'averageMonthlyRecurringSpending': json['averageMonthlyRecurringSpending'] == null ? undefined : json['averageMonthlyRecurringSpending'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'profileType': json['profileType'] == null ? undefined : FinancialUserProfileTypeFromJSON(json['profileType']),
    };
}

export function ExpenseMetricsFinancialSubProfileMetricsToJSON(value?: ExpenseMetricsFinancialSubProfileMetrics | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'month': value['month'],
        'spentLastWeek': value['spentLastWeek'],
        'spentLastMonth': value['spentLastMonth'],
        'spentLastSixMonths': value['spentLastSixMonths'],
        'averageMonthlyDiscretionarySpending': value['averageMonthlyDiscretionarySpending'],
        'averageMonthlyRecurringSpending': value['averageMonthlyRecurringSpending'],
        'userId': value['userId'],
        'profileType': FinancialUserProfileTypeToJSON(value['profileType']),
    };
}

