/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AccountBalanceHistory } from './AccountBalanceHistory';
import {
    AccountBalanceHistoryFromJSON,
    AccountBalanceHistoryFromJSONTyped,
    AccountBalanceHistoryToJSON,
} from './AccountBalanceHistory';

/**
 * 
 * @export
 * @interface GetAccountBalanceHistoryResponse
 */
export interface GetAccountBalanceHistoryResponse {
    /**
     * 
     * @type {Array<AccountBalanceHistory>}
     * @memberof GetAccountBalanceHistoryResponse
     */
    accountBalanceHistory?: Array<AccountBalanceHistory>;
}

/**
 * Check if a given object implements the GetAccountBalanceHistoryResponse interface.
 */
export function instanceOfGetAccountBalanceHistoryResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetAccountBalanceHistoryResponseFromJSON(json: any): GetAccountBalanceHistoryResponse {
    return GetAccountBalanceHistoryResponseFromJSONTyped(json, false);
}

export function GetAccountBalanceHistoryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetAccountBalanceHistoryResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountBalanceHistory': !exists(json, 'accountBalanceHistory') ? undefined : ((json['accountBalanceHistory'] as Array<any>).map(AccountBalanceHistoryFromJSON)),
    };
}

export function GetAccountBalanceHistoryResponseToJSON(value?: GetAccountBalanceHistoryResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountBalanceHistory': value.accountBalanceHistory === undefined ? undefined : ((value.accountBalanceHistory as Array<any>).map(AccountBalanceHistoryToJSON)),
    };
}

