/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CategoryMetricsFinancialSubProfile } from './CategoryMetricsFinancialSubProfile';
import {
    CategoryMetricsFinancialSubProfileFromJSON,
    CategoryMetricsFinancialSubProfileFromJSONTyped,
    CategoryMetricsFinancialSubProfileToJSON,
} from './CategoryMetricsFinancialSubProfile';

/**
 * 
 * @export
 * @interface GetCategoryMetricsFinancialSubProfileOverTimeResponse
 */
export interface GetCategoryMetricsFinancialSubProfileOverTimeResponse {
    /**
     * 
     * @type {Array<CategoryMetricsFinancialSubProfile>}
     * @memberof GetCategoryMetricsFinancialSubProfileOverTimeResponse
     */
    data?: Array<CategoryMetricsFinancialSubProfile>;
}

/**
 * Check if a given object implements the GetCategoryMetricsFinancialSubProfileOverTimeResponse interface.
 */
export function instanceOfGetCategoryMetricsFinancialSubProfileOverTimeResponse(value: object): boolean {
    return true;
}

export function GetCategoryMetricsFinancialSubProfileOverTimeResponseFromJSON(json: any): GetCategoryMetricsFinancialSubProfileOverTimeResponse {
    return GetCategoryMetricsFinancialSubProfileOverTimeResponseFromJSONTyped(json, false);
}

export function GetCategoryMetricsFinancialSubProfileOverTimeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCategoryMetricsFinancialSubProfileOverTimeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CategoryMetricsFinancialSubProfileFromJSON)),
    };
}

export function GetCategoryMetricsFinancialSubProfileOverTimeResponseToJSON(value?: GetCategoryMetricsFinancialSubProfileOverTimeResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CategoryMetricsFinancialSubProfileToJSON)),
    };
}

