/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCannyUserSSOTokenResponse
 */
export interface GetCannyUserSSOTokenResponse {
    /**
     * 
     * @type {string}
     * @memberof GetCannyUserSSOTokenResponse
     */
    token?: string;
}

/**
 * Check if a given object implements the GetCannyUserSSOTokenResponse interface.
 */
export function instanceOfGetCannyUserSSOTokenResponse(value: object): boolean {
    return true;
}

export function GetCannyUserSSOTokenResponseFromJSON(json: any): GetCannyUserSSOTokenResponse {
    return GetCannyUserSSOTokenResponseFromJSONTyped(json, false);
}

export function GetCannyUserSSOTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCannyUserSSOTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function GetCannyUserSSOTokenResponseToJSON(value?: GetCannyUserSSOTokenResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'token': value['token'],
    };
}

