/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccountBalanceHistory } from './AccountBalanceHistory';
import {
    AccountBalanceHistoryFromJSON,
    AccountBalanceHistoryFromJSONTyped,
    AccountBalanceHistoryToJSON,
} from './AccountBalanceHistory';

/**
 * 
 * @export
 * @interface GetHistoricalAccountBalanceResponse
 */
export interface GetHistoricalAccountBalanceResponse {
    /**
     * 
     * @type {Array<AccountBalanceHistory>}
     * @memberof GetHistoricalAccountBalanceResponse
     */
    historicalAccountBalance?: Array<AccountBalanceHistory>;
}

/**
 * Check if a given object implements the GetHistoricalAccountBalanceResponse interface.
 */
export function instanceOfGetHistoricalAccountBalanceResponse(value: object): boolean {
    return true;
}

export function GetHistoricalAccountBalanceResponseFromJSON(json: any): GetHistoricalAccountBalanceResponse {
    return GetHistoricalAccountBalanceResponseFromJSONTyped(json, false);
}

export function GetHistoricalAccountBalanceResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetHistoricalAccountBalanceResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'historicalAccountBalance': json['historicalAccountBalance'] == null ? undefined : ((json['historicalAccountBalance'] as Array<any>).map(AccountBalanceHistoryFromJSON)),
    };
}

export function GetHistoricalAccountBalanceResponseToJSON(value?: GetHistoricalAccountBalanceResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'historicalAccountBalance': value['historicalAccountBalance'] == null ? undefined : ((value['historicalAccountBalance'] as Array<any>).map(AccountBalanceHistoryToJSON)),
    };
}

