/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
} from './Link';

/**
 * 
 * @export
 * @interface GetLinksResponse
 */
export interface GetLinksResponse {
    /**
     * 
     * @type {Array<Link>}
     * @memberof GetLinksResponse
     */
    links?: Array<Link>;
}

/**
 * Check if a given object implements the GetLinksResponse interface.
 */
export function instanceOfGetLinksResponse(value: object): boolean {
    return true;
}

export function GetLinksResponseFromJSON(json: any): GetLinksResponse {
    return GetLinksResponseFromJSONTyped(json, false);
}

export function GetLinksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetLinksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'links': json['links'] == null ? undefined : ((json['links'] as Array<any>).map(LinkFromJSON)),
    };
}

export function GetLinksResponseToJSON(value?: GetLinksResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'links': value['links'] == null ? undefined : ((value['links'] as Array<any>).map(LinkToJSON)),
    };
}

