/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MonthlyTotalQuantityBySecurityAndUser } from './MonthlyTotalQuantityBySecurityAndUser';
import {
    MonthlyTotalQuantityBySecurityAndUserFromJSON,
    MonthlyTotalQuantityBySecurityAndUserFromJSONTyped,
    MonthlyTotalQuantityBySecurityAndUserToJSON,
} from './MonthlyTotalQuantityBySecurityAndUser';

/**
 * 
 * @export
 * @interface GetMonthlyTotalQuantityBySecurityAndUserResponse
 */
export interface GetMonthlyTotalQuantityBySecurityAndUserResponse {
    /**
     * 
     * @type {Array<MonthlyTotalQuantityBySecurityAndUser>}
     * @memberof GetMonthlyTotalQuantityBySecurityAndUserResponse
     */
    monthlyTotalQuantityBySecurityAndUser?: Array<MonthlyTotalQuantityBySecurityAndUser>;
    /**
     * 
     * @type {string}
     * @memberof GetMonthlyTotalQuantityBySecurityAndUserResponse
     */
    nextPageNumber?: string;
}

/**
 * Check if a given object implements the GetMonthlyTotalQuantityBySecurityAndUserResponse interface.
 */
export function instanceOfGetMonthlyTotalQuantityBySecurityAndUserResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetMonthlyTotalQuantityBySecurityAndUserResponseFromJSON(json: any): GetMonthlyTotalQuantityBySecurityAndUserResponse {
    return GetMonthlyTotalQuantityBySecurityAndUserResponseFromJSONTyped(json, false);
}

export function GetMonthlyTotalQuantityBySecurityAndUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMonthlyTotalQuantityBySecurityAndUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'monthlyTotalQuantityBySecurityAndUser': !exists(json, 'monthlyTotalQuantityBySecurityAndUser') ? undefined : ((json['monthlyTotalQuantityBySecurityAndUser'] as Array<any>).map(MonthlyTotalQuantityBySecurityAndUserFromJSON)),
        'nextPageNumber': !exists(json, 'nextPageNumber') ? undefined : json['nextPageNumber'],
    };
}

export function GetMonthlyTotalQuantityBySecurityAndUserResponseToJSON(value?: GetMonthlyTotalQuantityBySecurityAndUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'monthlyTotalQuantityBySecurityAndUser': value.monthlyTotalQuantityBySecurityAndUser === undefined ? undefined : ((value.monthlyTotalQuantityBySecurityAndUser as Array<any>).map(MonthlyTotalQuantityBySecurityAndUserToJSON)),
        'nextPageNumber': value.nextPageNumber,
    };
}

