/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Milestone } from './Milestone';
import {
    MilestoneFromJSON,
    MilestoneFromJSONTyped,
    MilestoneToJSON,
} from './Milestone';

/**
 * 
 * @export
 * @interface GetMilestonesBySmartGoalIdResponse
 */
export interface GetMilestonesBySmartGoalIdResponse {
    /**
     * 
     * @type {Array<Milestone>}
     * @memberof GetMilestonesBySmartGoalIdResponse
     */
    milestones?: Array<Milestone>;
}

/**
 * Check if a given object implements the GetMilestonesBySmartGoalIdResponse interface.
 */
export function instanceOfGetMilestonesBySmartGoalIdResponse(value: object): boolean {
    return true;
}

export function GetMilestonesBySmartGoalIdResponseFromJSON(json: any): GetMilestonesBySmartGoalIdResponse {
    return GetMilestonesBySmartGoalIdResponseFromJSONTyped(json, false);
}

export function GetMilestonesBySmartGoalIdResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMilestonesBySmartGoalIdResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'milestones': json['milestones'] == null ? undefined : ((json['milestones'] as Array<any>).map(MilestoneFromJSON)),
    };
}

export function GetMilestonesBySmartGoalIdResponseToJSON(value?: GetMilestonesBySmartGoalIdResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'milestones': value['milestones'] == null ? undefined : ((value['milestones'] as Array<any>).map(MilestoneToJSON)),
    };
}

