/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MonthlyIncome } from './MonthlyIncome';
import {
    MonthlyIncomeFromJSON,
    MonthlyIncomeFromJSONTyped,
    MonthlyIncomeToJSON,
} from './MonthlyIncome';

/**
 * 
 * @export
 * @interface GetMonthlyIncomeResponse
 */
export interface GetMonthlyIncomeResponse {
    /**
     * 
     * @type {Array<MonthlyIncome>}
     * @memberof GetMonthlyIncomeResponse
     */
    monthlyIncomes?: Array<MonthlyIncome>;
    /**
     * 
     * @type {string}
     * @memberof GetMonthlyIncomeResponse
     */
    nextPageNumber?: string;
}

/**
 * Check if a given object implements the GetMonthlyIncomeResponse interface.
 */
export function instanceOfGetMonthlyIncomeResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetMonthlyIncomeResponseFromJSON(json: any): GetMonthlyIncomeResponse {
    return GetMonthlyIncomeResponseFromJSONTyped(json, false);
}

export function GetMonthlyIncomeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetMonthlyIncomeResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'monthlyIncomes': !exists(json, 'monthlyIncomes') ? undefined : ((json['monthlyIncomes'] as Array<any>).map(MonthlyIncomeFromJSON)),
        'nextPageNumber': !exists(json, 'nextPageNumber') ? undefined : json['nextPageNumber'],
    };
}

export function GetMonthlyIncomeResponseToJSON(value?: GetMonthlyIncomeResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'monthlyIncomes': value.monthlyIncomes === undefined ? undefined : ((value.monthlyIncomes as Array<any>).map(MonthlyIncomeToJSON)),
        'nextPageNumber': value.nextPageNumber,
    };
}

