/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Pocket } from './Pocket';
import {
    PocketFromJSON,
    PocketFromJSONTyped,
    PocketToJSON,
} from './Pocket';

/**
 * 
 * @export
 * @interface GetPocketResponse
 */
export interface GetPocketResponse {
    /**
     * 
     * @type {Pocket}
     * @memberof GetPocketResponse
     */
    pocket?: Pocket;
}

/**
 * Check if a given object implements the GetPocketResponse interface.
 */
export function instanceOfGetPocketResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetPocketResponseFromJSON(json: any): GetPocketResponse {
    return GetPocketResponseFromJSONTyped(json, false);
}

export function GetPocketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPocketResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pocket': !exists(json, 'pocket') ? undefined : PocketFromJSON(json['pocket']),
    };
}

export function GetPocketResponseToJSON(value?: GetPocketResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'pocket': PocketToJSON(value.pocket),
    };
}

