/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { PlaidAccountTransaction } from './PlaidAccountTransaction';
import {
    PlaidAccountTransactionFromJSON,
    PlaidAccountTransactionFromJSONTyped,
    PlaidAccountTransactionToJSON,
} from './PlaidAccountTransaction';

/**
 * 
 * @export
 * @interface GetTransactionsForPastMonthResponse
 */
export interface GetTransactionsForPastMonthResponse {
    /**
     * 
     * @type {Array<PlaidAccountTransaction>}
     * @memberof GetTransactionsForPastMonthResponse
     */
    transactions?: Array<PlaidAccountTransaction>;
    /**
     * 
     * @type {number}
     * @memberof GetTransactionsForPastMonthResponse
     */
    currentPage?: number;
    /**
     * 
     * @type {number}
     * @memberof GetTransactionsForPastMonthResponse
     */
    totalPages?: number;
    /**
     * 
     * @type {string}
     * @memberof GetTransactionsForPastMonthResponse
     */
    totalTransactions?: string;
}

/**
 * Check if a given object implements the GetTransactionsForPastMonthResponse interface.
 */
export function instanceOfGetTransactionsForPastMonthResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetTransactionsForPastMonthResponseFromJSON(json: any): GetTransactionsForPastMonthResponse {
    return GetTransactionsForPastMonthResponseFromJSONTyped(json, false);
}

export function GetTransactionsForPastMonthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransactionsForPastMonthResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactions': !exists(json, 'transactions') ? undefined : ((json['transactions'] as Array<any>).map(PlaidAccountTransactionFromJSON)),
        'currentPage': !exists(json, 'currentPage') ? undefined : json['currentPage'],
        'totalPages': !exists(json, 'totalPages') ? undefined : json['totalPages'],
        'totalTransactions': !exists(json, 'totalTransactions') ? undefined : json['totalTransactions'],
    };
}

export function GetTransactionsForPastMonthResponseToJSON(value?: GetTransactionsForPastMonthResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactions': value.transactions === undefined ? undefined : ((value.transactions as Array<any>).map(PlaidAccountTransactionToJSON)),
        'currentPage': value.currentPage,
        'totalPages': value.totalPages,
        'totalTransactions': value.totalTransactions,
    };
}

