/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaidAccountTransaction } from './PlaidAccountTransaction';
import {
    PlaidAccountTransactionFromJSON,
    PlaidAccountTransactionFromJSONTyped,
    PlaidAccountTransactionToJSON,
} from './PlaidAccountTransaction';

/**
 * 
 * @export
 * @interface GetTransactionResponse
 */
export interface GetTransactionResponse {
    /**
     * 
     * @type {PlaidAccountTransaction}
     * @memberof GetTransactionResponse
     */
    transaction?: PlaidAccountTransaction;
}

/**
 * Check if a given object implements the GetTransactionResponse interface.
 */
export function instanceOfGetTransactionResponse(value: object): boolean {
    return true;
}

export function GetTransactionResponseFromJSON(json: any): GetTransactionResponse {
    return GetTransactionResponseFromJSONTyped(json, false);
}

export function GetTransactionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransactionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transaction': json['transaction'] == null ? undefined : PlaidAccountTransactionFromJSON(json['transaction']),
    };
}

export function GetTransactionResponseToJSON(value?: GetTransactionResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transaction': PlaidAccountTransactionToJSON(value['transaction']),
    };
}

