/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TransactionAggregatesByMonth } from './TransactionAggregatesByMonth';
import {
    TransactionAggregatesByMonthFromJSON,
    TransactionAggregatesByMonthFromJSONTyped,
    TransactionAggregatesByMonthToJSON,
} from './TransactionAggregatesByMonth';

/**
 * 
 * @export
 * @interface GetTransactionAggregatesResponse
 */
export interface GetTransactionAggregatesResponse {
    /**
     * 
     * @type {Array<TransactionAggregatesByMonth>}
     * @memberof GetTransactionAggregatesResponse
     */
    transactionAggregates?: Array<TransactionAggregatesByMonth>;
    /**
     * 
     * @type {string}
     * @memberof GetTransactionAggregatesResponse
     */
    nextPageNumber?: string;
}

/**
 * Check if a given object implements the GetTransactionAggregatesResponse interface.
 */
export function instanceOfGetTransactionAggregatesResponse(value: object): boolean {
    return true;
}

export function GetTransactionAggregatesResponseFromJSON(json: any): GetTransactionAggregatesResponse {
    return GetTransactionAggregatesResponseFromJSONTyped(json, false);
}

export function GetTransactionAggregatesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetTransactionAggregatesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transactionAggregates': json['transactionAggregates'] == null ? undefined : ((json['transactionAggregates'] as Array<any>).map(TransactionAggregatesByMonthFromJSON)),
        'nextPageNumber': json['nextPageNumber'] == null ? undefined : json['nextPageNumber'],
    };
}

export function GetTransactionAggregatesResponseToJSON(value?: GetTransactionAggregatesResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transactionAggregates': value['transactionAggregates'] == null ? undefined : ((value['transactionAggregates'] as Array<any>).map(TransactionAggregatesByMonthToJSON)),
        'nextPageNumber': value['nextPageNumber'],
    };
}

