/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BusinessAccount } from './BusinessAccount';
import {
    BusinessAccountFromJSON,
    BusinessAccountFromJSONTyped,
    BusinessAccountToJSON,
} from './BusinessAccount';
import type { UserAccount } from './UserAccount';
import {
    UserAccountFromJSON,
    UserAccountFromJSONTyped,
    UserAccountToJSON,
} from './UserAccount';

/**
 * 
 * @export
 * @interface GetUserByUsernameV2Response
 */
export interface GetUserByUsernameV2Response {
    /**
     * 
     * @type {UserAccount}
     * @memberof GetUserByUsernameV2Response
     */
    userAccount?: UserAccount;
    /**
     * 
     * @type {BusinessAccount}
     * @memberof GetUserByUsernameV2Response
     */
    businessAccount?: BusinessAccount;
    /**
     * 
     * @type {string}
     * @memberof GetUserByUsernameV2Response
     */
    ssoToken?: string;
}

/**
 * Check if a given object implements the GetUserByUsernameV2Response interface.
 */
export function instanceOfGetUserByUsernameV2Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function GetUserByUsernameV2ResponseFromJSON(json: any): GetUserByUsernameV2Response {
    return GetUserByUsernameV2ResponseFromJSONTyped(json, false);
}

export function GetUserByUsernameV2ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserByUsernameV2Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userAccount': !exists(json, 'userAccount') ? undefined : UserAccountFromJSON(json['userAccount']),
        'businessAccount': !exists(json, 'businessAccount') ? undefined : BusinessAccountFromJSON(json['businessAccount']),
        'ssoToken': !exists(json, 'ssoToken') ? undefined : json['ssoToken'],
    };
}

export function GetUserByUsernameV2ResponseToJSON(value?: GetUserByUsernameV2Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userAccount': UserAccountToJSON(value.userAccount),
        'businessAccount': BusinessAccountToJSON(value.businessAccount),
        'ssoToken': value.ssoToken,
    };
}

