/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessAccount } from './BusinessAccount';
import {
    BusinessAccountFromJSON,
    BusinessAccountFromJSONTyped,
    BusinessAccountToJSON,
} from './BusinessAccount';
import type { UserAccount } from './UserAccount';
import {
    UserAccountFromJSON,
    UserAccountFromJSONTyped,
    UserAccountToJSON,
} from './UserAccount';

/**
 * 
 * @export
 * @interface GetUserByUsernameV2Response
 */
export interface GetUserByUsernameV2Response {
    /**
     * 
     * @type {UserAccount}
     * @memberof GetUserByUsernameV2Response
     */
    userAccount?: UserAccount;
    /**
     * 
     * @type {BusinessAccount}
     * @memberof GetUserByUsernameV2Response
     */
    businessAccount?: BusinessAccount;
    /**
     * 
     * @type {string}
     * @memberof GetUserByUsernameV2Response
     */
    ssoToken?: string;
}

/**
 * Check if a given object implements the GetUserByUsernameV2Response interface.
 */
export function instanceOfGetUserByUsernameV2Response(value: object): boolean {
    return true;
}

export function GetUserByUsernameV2ResponseFromJSON(json: any): GetUserByUsernameV2Response {
    return GetUserByUsernameV2ResponseFromJSONTyped(json, false);
}

export function GetUserByUsernameV2ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserByUsernameV2Response {
    if (json == null) {
        return json;
    }
    return {
        
        'userAccount': json['userAccount'] == null ? undefined : UserAccountFromJSON(json['userAccount']),
        'businessAccount': json['businessAccount'] == null ? undefined : BusinessAccountFromJSON(json['businessAccount']),
        'ssoToken': json['ssoToken'] == null ? undefined : json['ssoToken'],
    };
}

export function GetUserByUsernameV2ResponseToJSON(value?: GetUserByUsernameV2Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userAccount': UserAccountToJSON(value['userAccount']),
        'businessAccount': BusinessAccountToJSON(value['businessAccount']),
        'ssoToken': value['ssoToken'],
    };
}

