/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserAccount } from './UserAccount';
import {
    UserAccountFromJSON,
    UserAccountFromJSONTyped,
    UserAccountToJSON,
} from './UserAccount';

/**
 * 
 * @export
 * @interface GetUserByEmailResponse
 */
export interface GetUserByEmailResponse {
    /**
     * 
     * @type {UserAccount}
     * @memberof GetUserByEmailResponse
     */
    account?: UserAccount;
}

/**
 * Check if a given object implements the GetUserByEmailResponse interface.
 */
export function instanceOfGetUserByEmailResponse(value: object): boolean {
    return true;
}

export function GetUserByEmailResponseFromJSON(json: any): GetUserByEmailResponse {
    return GetUserByEmailResponseFromJSONTyped(json, false);
}

export function GetUserByEmailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetUserByEmailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'account': json['account'] == null ? undefined : UserAccountFromJSON(json['account']),
    };
}

export function GetUserByEmailResponseToJSON(value?: GetUserByEmailResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'account': UserAccountToJSON(value['account']),
    };
}

