/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheckResponse
 */
export interface HealthCheckResponse {
    /**
     * 
     * @type {boolean}
     * @memberof HealthCheckResponse
     */
    healthy?: boolean;
}

/**
 * Check if a given object implements the HealthCheckResponse interface.
 */
export function instanceOfHealthCheckResponse(value: object): boolean {
    return true;
}

export function HealthCheckResponseFromJSON(json: any): HealthCheckResponse {
    return HealthCheckResponseFromJSONTyped(json, false);
}

export function HealthCheckResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheckResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'healthy': json['healthy'] == null ? undefined : json['healthy'],
    };
}

export function HealthCheckResponseToJSON(value?: HealthCheckResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'healthy': value['healthy'],
    };
}

