/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CompanyProfile } from './CompanyProfile';
import {
    CompanyProfileFromJSON,
    CompanyProfileFromJSONTyped,
    CompanyProfileToJSON,
} from './CompanyProfile';
import type { Employee } from './Employee';
import {
    EmployeeFromJSON,
    EmployeeFromJSONTyped,
    EmployeeToJSON,
} from './Employee';
import type { EmployerBenefits } from './EmployerBenefits';
import {
    EmployerBenefitsFromJSON,
    EmployerBenefitsFromJSONTyped,
    EmployerBenefitsToJSON,
} from './EmployerBenefits';
import type { EmployerPayrollRun } from './EmployerPayrollRun';
import {
    EmployerPayrollRunFromJSON,
    EmployerPayrollRunFromJSONTyped,
    EmployerPayrollRunToJSON,
} from './EmployerPayrollRun';

/**
 * 
 * @export
 * @interface HrisLinkedAccount
 */
export interface HrisLinkedAccount {
    /**
     * 
     * @type {string}
     * @memberof HrisLinkedAccount
     */
    id?: string;
    /**
     * 
     * @type {CompanyProfile}
     * @memberof HrisLinkedAccount
     */
    profile?: CompanyProfile;
    /**
     * 
     * @type {Array<EmployerBenefits>}
     * @memberof HrisLinkedAccount
     */
    benefitPlans?: Array<EmployerBenefits>;
    /**
     * 
     * @type {Array<Employee>}
     * @memberof HrisLinkedAccount
     */
    employees?: Array<Employee>;
    /**
     * 
     * @type {Array<EmployerPayrollRun>}
     * @memberof HrisLinkedAccount
     */
    payrollRuns?: Array<EmployerPayrollRun>;
}

/**
 * Check if a given object implements the HrisLinkedAccount interface.
 */
export function instanceOfHrisLinkedAccount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function HrisLinkedAccountFromJSON(json: any): HrisLinkedAccount {
    return HrisLinkedAccountFromJSONTyped(json, false);
}

export function HrisLinkedAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): HrisLinkedAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'profile': !exists(json, 'profile') ? undefined : CompanyProfileFromJSON(json['profile']),
        'benefitPlans': !exists(json, 'benefitPlans') ? undefined : ((json['benefitPlans'] as Array<any>).map(EmployerBenefitsFromJSON)),
        'employees': !exists(json, 'employees') ? undefined : ((json['employees'] as Array<any>).map(EmployeeFromJSON)),
        'payrollRuns': !exists(json, 'payrollRuns') ? undefined : ((json['payrollRuns'] as Array<any>).map(EmployerPayrollRunFromJSON)),
    };
}

export function HrisLinkedAccountToJSON(value?: HrisLinkedAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'profile': CompanyProfileToJSON(value.profile),
        'benefitPlans': value.benefitPlans === undefined ? undefined : ((value.benefitPlans as Array<any>).map(EmployerBenefitsToJSON)),
        'employees': value.employees === undefined ? undefined : ((value.employees as Array<any>).map(EmployeeToJSON)),
        'payrollRuns': value.payrollRuns === undefined ? undefined : ((value.payrollRuns as Array<any>).map(EmployerPayrollRunToJSON)),
    };
}

