/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialUserProfileType } from './FinancialUserProfileType';
import {
    FinancialUserProfileTypeFromJSON,
    FinancialUserProfileTypeFromJSONTyped,
    FinancialUserProfileTypeToJSON,
} from './FinancialUserProfileType';

/**
 * IncomeExpenseRatio
 * This message is used to represent the income expense ratio of a user.
 * @export
 * @interface IncomeExpenseRatio
 */
export interface IncomeExpenseRatio {
    /**
     * 
     * @type {number}
     * @memberof IncomeExpenseRatio
     */
    month?: number;
    /**
     * 
     * @type {number}
     * @memberof IncomeExpenseRatio
     */
    ratio?: number;
    /**
     * 
     * @type {string}
     * @memberof IncomeExpenseRatio
     */
    userId?: string;
    /**
     * 
     * @type {FinancialUserProfileType}
     * @memberof IncomeExpenseRatio
     */
    profileType?: FinancialUserProfileType;
}

/**
 * Check if a given object implements the IncomeExpenseRatio interface.
 */
export function instanceOfIncomeExpenseRatio(value: object): boolean {
    return true;
}

export function IncomeExpenseRatioFromJSON(json: any): IncomeExpenseRatio {
    return IncomeExpenseRatioFromJSONTyped(json, false);
}

export function IncomeExpenseRatioFromJSONTyped(json: any, ignoreDiscriminator: boolean): IncomeExpenseRatio {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'] == null ? undefined : json['month'],
        'ratio': json['ratio'] == null ? undefined : json['ratio'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'profileType': json['profileType'] == null ? undefined : FinancialUserProfileTypeFromJSON(json['profileType']),
    };
}

export function IncomeExpenseRatioToJSON(value?: IncomeExpenseRatio | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'month': value['month'],
        'ratio': value['ratio'],
        'userId': value['userId'],
        'profileType': FinancialUserProfileTypeToJSON(value['profileType']),
    };
}

