/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InvestmentSecurity
 */
export interface InvestmentSecurity {
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof InvestmentSecurity
     */
    closePrice?: number;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    closePriceAsOf?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    cusip?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    institutionId?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    institutionSecurityId?: string;
    /**
     * 
     * @type {boolean}
     * @memberof InvestmentSecurity
     */
    isCashEquivalent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    isin?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    isoCurrencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    proxySecurityId?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    securityId?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    sedol?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    tickerSymbol?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    unofficialCurrencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof InvestmentSecurity
     */
    updateDatetime?: string;
}

/**
 * Check if a given object implements the InvestmentSecurity interface.
 */
export function instanceOfInvestmentSecurity(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InvestmentSecurityFromJSON(json: any): InvestmentSecurity {
    return InvestmentSecurityFromJSONTyped(json, false);
}

export function InvestmentSecurityFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvestmentSecurity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'closePrice': !exists(json, 'closePrice') ? undefined : json['closePrice'],
        'closePriceAsOf': !exists(json, 'closePriceAsOf') ? undefined : json['closePriceAsOf'],
        'cusip': !exists(json, 'cusip') ? undefined : json['cusip'],
        'institutionId': !exists(json, 'institutionId') ? undefined : json['institutionId'],
        'institutionSecurityId': !exists(json, 'institutionSecurityId') ? undefined : json['institutionSecurityId'],
        'isCashEquivalent': !exists(json, 'isCashEquivalent') ? undefined : json['isCashEquivalent'],
        'isin': !exists(json, 'isin') ? undefined : json['isin'],
        'isoCurrencyCode': !exists(json, 'isoCurrencyCode') ? undefined : json['isoCurrencyCode'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'proxySecurityId': !exists(json, 'proxySecurityId') ? undefined : json['proxySecurityId'],
        'securityId': !exists(json, 'securityId') ? undefined : json['securityId'],
        'sedol': !exists(json, 'sedol') ? undefined : json['sedol'],
        'tickerSymbol': !exists(json, 'tickerSymbol') ? undefined : json['tickerSymbol'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'unofficialCurrencyCode': !exists(json, 'unofficialCurrencyCode') ? undefined : json['unofficialCurrencyCode'],
        'updateDatetime': !exists(json, 'updateDatetime') ? undefined : json['updateDatetime'],
    };
}

export function InvestmentSecurityToJSON(value?: InvestmentSecurity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'closePrice': value.closePrice,
        'closePriceAsOf': value.closePriceAsOf,
        'cusip': value.cusip,
        'institutionId': value.institutionId,
        'institutionSecurityId': value.institutionSecurityId,
        'isCashEquivalent': value.isCashEquivalent,
        'isin': value.isin,
        'isoCurrencyCode': value.isoCurrencyCode,
        'name': value.name,
        'proxySecurityId': value.proxySecurityId,
        'securityId': value.securityId,
        'sedol': value.sedol,
        'tickerSymbol': value.tickerSymbol,
        'type': value.type,
        'unofficialCurrencyCode': value.unofficialCurrencyCode,
        'updateDatetime': value.updateDatetime,
    };
}

