/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The Invoice object represents an itemized record of goods and/or services sold to a customer.
 * @export
 * @interface InvoiceLineItem
 */
export interface InvoiceLineItem {
    /**
     * 
     * @type {string}
     * @memberof InvoiceLineItem
     */
    id?: string;
    /**
     * The third-party API ID of the matching object.
     * @type {string}
     * @memberof InvoiceLineItem
     */
    remoteId?: string;
    /**
     * The line item's description.
     * @type {string}
     * @memberof InvoiceLineItem
     */
    description?: string;
    /**
     * The line item's unit price.
     * @type {number}
     * @memberof InvoiceLineItem
     */
    unitPrice?: number;
    /**
     * The line item's quantity.
     * @type {number}
     * @memberof InvoiceLineItem
     */
    quantity?: number;
    /**
     * The line item's total amount.
     * @type {number}
     * @memberof InvoiceLineItem
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof InvoiceLineItem
     */
    currency?: string;
    /**
     * The line item's exchange rate.
     * @type {string}
     * @memberof InvoiceLineItem
     */
    exchangeRate?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceLineItem
     */
    item?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceLineItem
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceLineItem
     */
    trackingCategory?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof InvoiceLineItem
     */
    trackingCategories?: Array<string>;
    /**
     * The company the line item belongs to.
     * @type {string}
     * @memberof InvoiceLineItem
     */
    company?: string;
    /**
     * 
     * @type {string}
     * @memberof InvoiceLineItem
     */
    mergeRecordId?: string;
    /**
     * Consider using google.protobuf.Timestamp
     * @type {Date}
     * @memberof InvoiceLineItem
     */
    modifiedAt?: Date;
}

/**
 * Check if a given object implements the InvoiceLineItem interface.
 */
export function instanceOfInvoiceLineItem(value: object): boolean {
    return true;
}

export function InvoiceLineItemFromJSON(json: any): InvoiceLineItem {
    return InvoiceLineItemFromJSONTyped(json, false);
}

export function InvoiceLineItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): InvoiceLineItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'remoteId': json['remoteId'] == null ? undefined : json['remoteId'],
        'description': json['description'] == null ? undefined : json['description'],
        'unitPrice': json['unitPrice'] == null ? undefined : json['unitPrice'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'exchangeRate': json['exchangeRate'] == null ? undefined : json['exchangeRate'],
        'item': json['item'] == null ? undefined : json['item'],
        'account': json['account'] == null ? undefined : json['account'],
        'trackingCategory': json['trackingCategory'] == null ? undefined : json['trackingCategory'],
        'trackingCategories': json['trackingCategories'] == null ? undefined : json['trackingCategories'],
        'company': json['company'] == null ? undefined : json['company'],
        'mergeRecordId': json['mergeRecordId'] == null ? undefined : json['mergeRecordId'],
        'modifiedAt': json['modifiedAt'] == null ? undefined : (new Date(json['modifiedAt'])),
    };
}

export function InvoiceLineItemToJSON(value?: InvoiceLineItem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'remoteId': value['remoteId'],
        'description': value['description'],
        'unitPrice': value['unitPrice'],
        'quantity': value['quantity'],
        'totalAmount': value['totalAmount'],
        'currency': value['currency'],
        'exchangeRate': value['exchangeRate'],
        'item': value['item'],
        'account': value['account'],
        'trackingCategory': value['trackingCategory'],
        'trackingCategories': value['trackingCategories'],
        'company': value['company'],
        'mergeRecordId': value['mergeRecordId'],
        'modifiedAt': value['modifiedAt'] == null ? undefined : ((value['modifiedAt']).toISOString()),
    };
}

