/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * The JournalLine object is used to represent a journal entry's line items.
 * @export
 * @interface JournalLine
 */
export interface JournalLine {
    /**
     * 
     * @type {string}
     * @memberof JournalLine
     */
    id?: string;
    /**
     * The third-party API ID of the matching object.
     * @type {string}
     * @memberof JournalLine
     */
    remoteId?: string;
    /**
     * 
     * @type {string}
     * @memberof JournalLine
     */
    account?: string;
    /**
     * The value of the line item including taxes and other fees.
     * 
     * Might want to use double or a more precise type
     * @type {number}
     * @memberof JournalLine
     */
    netAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof JournalLine
     */
    trackingCategory?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof JournalLine
     */
    trackingCategories?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof JournalLine
     */
    contact?: string;
    /**
     * The company the journal entry belongs to.
     * @type {string}
     * @memberof JournalLine
     */
    company?: string;
    /**
     * The line's description.
     * @type {string}
     * @memberof JournalLine
     */
    description?: string;
    /**
     * The journal line item's exchange rate.
     * 
     * Assuming string due to the example provided, but could be float or double.
     * @type {string}
     * @memberof JournalLine
     */
    exchangeRate?: string;
    /**
     * 
     * @type {Date}
     * @memberof JournalLine
     */
    modifiedAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof JournalLine
     */
    createdAt?: Date;
}

/**
 * Check if a given object implements the JournalLine interface.
 */
export function instanceOfJournalLine(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function JournalLineFromJSON(json: any): JournalLine {
    return JournalLineFromJSONTyped(json, false);
}

export function JournalLineFromJSONTyped(json: any, ignoreDiscriminator: boolean): JournalLine {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'remoteId': !exists(json, 'remoteId') ? undefined : json['remoteId'],
        'account': !exists(json, 'account') ? undefined : json['account'],
        'netAmount': !exists(json, 'netAmount') ? undefined : json['netAmount'],
        'trackingCategory': !exists(json, 'trackingCategory') ? undefined : json['trackingCategory'],
        'trackingCategories': !exists(json, 'trackingCategories') ? undefined : json['trackingCategories'],
        'contact': !exists(json, 'contact') ? undefined : json['contact'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'exchangeRate': !exists(json, 'exchangeRate') ? undefined : json['exchangeRate'],
        'modifiedAt': !exists(json, 'modifiedAt') ? undefined : (new Date(json['modifiedAt'])),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
    };
}

export function JournalLineToJSON(value?: JournalLine | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'remoteId': value.remoteId,
        'account': value.account,
        'netAmount': value.netAmount,
        'trackingCategory': value.trackingCategory,
        'trackingCategories': value.trackingCategories,
        'contact': value.contact,
        'company': value.company,
        'description': value.description,
        'exchangeRate': value.exchangeRate,
        'modifiedAt': value.modifiedAt === undefined ? undefined : (value.modifiedAt.toISOString()),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
    };
}

