/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaidAccountTransaction } from './PlaidAccountTransaction';
import {
    PlaidAccountTransactionFromJSON,
    PlaidAccountTransactionFromJSONTyped,
    PlaidAccountTransactionToJSON,
} from './PlaidAccountTransaction';

/**
 * 
 * @export
 * @interface ListTransactionsAcrossAllAccountsResponse
 */
export interface ListTransactionsAcrossAllAccountsResponse {
    /**
     * 
     * @type {string}
     * @memberof ListTransactionsAcrossAllAccountsResponse
     */
    nextPage?: string;
    /**
     * 
     * @type {Array<PlaidAccountTransaction>}
     * @memberof ListTransactionsAcrossAllAccountsResponse
     */
    transactions?: Array<PlaidAccountTransaction>;
}

/**
 * Check if a given object implements the ListTransactionsAcrossAllAccountsResponse interface.
 */
export function instanceOfListTransactionsAcrossAllAccountsResponse(value: object): boolean {
    return true;
}

export function ListTransactionsAcrossAllAccountsResponseFromJSON(json: any): ListTransactionsAcrossAllAccountsResponse {
    return ListTransactionsAcrossAllAccountsResponseFromJSONTyped(json, false);
}

export function ListTransactionsAcrossAllAccountsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListTransactionsAcrossAllAccountsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nextPage': json['nextPage'] == null ? undefined : json['nextPage'],
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(PlaidAccountTransactionFromJSON)),
    };
}

export function ListTransactionsAcrossAllAccountsResponseToJSON(value?: ListTransactionsAcrossAllAccountsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nextPage': value['nextPage'],
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(PlaidAccountTransactionToJSON)),
    };
}

