/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialUserProfileType } from './FinancialUserProfileType';
import {
    FinancialUserProfileTypeFromJSON,
    FinancialUserProfileTypeFromJSONTyped,
    FinancialUserProfileTypeToJSON,
} from './FinancialUserProfileType';

/**
 * MerchantMonthlyExpenditure
 * This message is used to represent the monthly expenditure of a merchant.
 * @export
 * @interface MerchantMonthlyExpenditure
 */
export interface MerchantMonthlyExpenditure {
    /**
     * 
     * @type {number}
     * @memberof MerchantMonthlyExpenditure
     */
    month?: number;
    /**
     * 
     * @type {string}
     * @memberof MerchantMonthlyExpenditure
     */
    merchantName?: string;
    /**
     * 
     * @type {number}
     * @memberof MerchantMonthlyExpenditure
     */
    totalSpending?: number;
    /**
     * 
     * @type {string}
     * @memberof MerchantMonthlyExpenditure
     */
    userId?: string;
    /**
     * 
     * @type {FinancialUserProfileType}
     * @memberof MerchantMonthlyExpenditure
     */
    profileType?: FinancialUserProfileType;
}

/**
 * Check if a given object implements the MerchantMonthlyExpenditure interface.
 */
export function instanceOfMerchantMonthlyExpenditure(value: object): boolean {
    return true;
}

export function MerchantMonthlyExpenditureFromJSON(json: any): MerchantMonthlyExpenditure {
    return MerchantMonthlyExpenditureFromJSONTyped(json, false);
}

export function MerchantMonthlyExpenditureFromJSONTyped(json: any, ignoreDiscriminator: boolean): MerchantMonthlyExpenditure {
    if (json == null) {
        return json;
    }
    return {
        
        'month': json['month'] == null ? undefined : json['month'],
        'merchantName': json['merchantName'] == null ? undefined : json['merchantName'],
        'totalSpending': json['totalSpending'] == null ? undefined : json['totalSpending'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'profileType': json['profileType'] == null ? undefined : FinancialUserProfileTypeFromJSON(json['profileType']),
    };
}

export function MerchantMonthlyExpenditureToJSON(value?: MerchantMonthlyExpenditure | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'month': value['month'],
        'merchantName': value['merchantName'],
        'totalSpending': value['totalSpending'],
        'userId': value['userId'],
        'profileType': FinancialUserProfileTypeToJSON(value['profileType']),
    };
}

