/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BankAccountStatus } from './BankAccountStatus';
import {
    BankAccountStatusFromJSON,
    BankAccountStatusFromJSONTyped,
    BankAccountStatusToJSON,
} from './BankAccountStatus';

/**
 * 
 * @export
 * @interface MortgageAccount
 */
export interface MortgageAccount {
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    plaidAccountId?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    accountNumber?: string;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    currentLateFee?: number;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    escrowBalance?: number;
    /**
     * 
     * @type {boolean}
     * @memberof MortgageAccount
     */
    hasPmi?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MortgageAccount
     */
    hasPrepaymentPenalty?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    lastPaymentAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    lastPaymentDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    loanTerm?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    loanTypeDescription?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    maturityDate?: string;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    nextMonthlyPayment?: number;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    nextPaymentDueDate?: string;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    originalPrincipalBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    originalPropertyValue?: number;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    outstandingPrincipalBalance?: number;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    paymentAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    paymentDate?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    originationDate?: string;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    originationPrincipalAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    pastDueAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    ytdInterestPaid?: number;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    ytdPrincipalPaid?: number;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    propertyAddressCity?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    propertyAddressState?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    propertyAddressStreet?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    propertyAddressPostalCode?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    propertyRegion?: string;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    propertyCountry?: string;
    /**
     * 
     * @type {number}
     * @memberof MortgageAccount
     */
    interestRatePercentage?: number;
    /**
     * 
     * @type {string}
     * @memberof MortgageAccount
     */
    interestRateType?: string;
    /**
     * 
     * @type {BankAccountStatus}
     * @memberof MortgageAccount
     */
    status?: BankAccountStatus;
}

/**
 * Check if a given object implements the MortgageAccount interface.
 */
export function instanceOfMortgageAccount(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function MortgageAccountFromJSON(json: any): MortgageAccount {
    return MortgageAccountFromJSONTyped(json, false);
}

export function MortgageAccountFromJSONTyped(json: any, ignoreDiscriminator: boolean): MortgageAccount {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'plaidAccountId': !exists(json, 'plaidAccountId') ? undefined : json['plaidAccountId'],
        'accountNumber': !exists(json, 'accountNumber') ? undefined : json['accountNumber'],
        'currentLateFee': !exists(json, 'currentLateFee') ? undefined : json['currentLateFee'],
        'escrowBalance': !exists(json, 'escrowBalance') ? undefined : json['escrowBalance'],
        'hasPmi': !exists(json, 'hasPmi') ? undefined : json['hasPmi'],
        'hasPrepaymentPenalty': !exists(json, 'hasPrepaymentPenalty') ? undefined : json['hasPrepaymentPenalty'],
        'lastPaymentAmount': !exists(json, 'lastPaymentAmount') ? undefined : json['lastPaymentAmount'],
        'lastPaymentDate': !exists(json, 'lastPaymentDate') ? undefined : json['lastPaymentDate'],
        'loanTerm': !exists(json, 'loanTerm') ? undefined : json['loanTerm'],
        'loanTypeDescription': !exists(json, 'loanTypeDescription') ? undefined : json['loanTypeDescription'],
        'maturityDate': !exists(json, 'maturityDate') ? undefined : json['maturityDate'],
        'nextMonthlyPayment': !exists(json, 'nextMonthlyPayment') ? undefined : json['nextMonthlyPayment'],
        'nextPaymentDueDate': !exists(json, 'nextPaymentDueDate') ? undefined : json['nextPaymentDueDate'],
        'originalPrincipalBalance': !exists(json, 'originalPrincipalBalance') ? undefined : json['originalPrincipalBalance'],
        'originalPropertyValue': !exists(json, 'originalPropertyValue') ? undefined : json['originalPropertyValue'],
        'outstandingPrincipalBalance': !exists(json, 'outstandingPrincipalBalance') ? undefined : json['outstandingPrincipalBalance'],
        'paymentAmount': !exists(json, 'paymentAmount') ? undefined : json['paymentAmount'],
        'paymentDate': !exists(json, 'paymentDate') ? undefined : json['paymentDate'],
        'originationDate': !exists(json, 'originationDate') ? undefined : json['originationDate'],
        'originationPrincipalAmount': !exists(json, 'originationPrincipalAmount') ? undefined : json['originationPrincipalAmount'],
        'pastDueAmount': !exists(json, 'pastDueAmount') ? undefined : json['pastDueAmount'],
        'ytdInterestPaid': !exists(json, 'ytdInterestPaid') ? undefined : json['ytdInterestPaid'],
        'ytdPrincipalPaid': !exists(json, 'ytdPrincipalPaid') ? undefined : json['ytdPrincipalPaid'],
        'propertyAddressCity': !exists(json, 'propertyAddressCity') ? undefined : json['propertyAddressCity'],
        'propertyAddressState': !exists(json, 'propertyAddressState') ? undefined : json['propertyAddressState'],
        'propertyAddressStreet': !exists(json, 'propertyAddressStreet') ? undefined : json['propertyAddressStreet'],
        'propertyAddressPostalCode': !exists(json, 'propertyAddressPostalCode') ? undefined : json['propertyAddressPostalCode'],
        'propertyRegion': !exists(json, 'propertyRegion') ? undefined : json['propertyRegion'],
        'propertyCountry': !exists(json, 'propertyCountry') ? undefined : json['propertyCountry'],
        'interestRatePercentage': !exists(json, 'interestRatePercentage') ? undefined : json['interestRatePercentage'],
        'interestRateType': !exists(json, 'interestRateType') ? undefined : json['interestRateType'],
        'status': !exists(json, 'status') ? undefined : BankAccountStatusFromJSON(json['status']),
    };
}

export function MortgageAccountToJSON(value?: MortgageAccount | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'plaidAccountId': value.plaidAccountId,
        'accountNumber': value.accountNumber,
        'currentLateFee': value.currentLateFee,
        'escrowBalance': value.escrowBalance,
        'hasPmi': value.hasPmi,
        'hasPrepaymentPenalty': value.hasPrepaymentPenalty,
        'lastPaymentAmount': value.lastPaymentAmount,
        'lastPaymentDate': value.lastPaymentDate,
        'loanTerm': value.loanTerm,
        'loanTypeDescription': value.loanTypeDescription,
        'maturityDate': value.maturityDate,
        'nextMonthlyPayment': value.nextMonthlyPayment,
        'nextPaymentDueDate': value.nextPaymentDueDate,
        'originalPrincipalBalance': value.originalPrincipalBalance,
        'originalPropertyValue': value.originalPropertyValue,
        'outstandingPrincipalBalance': value.outstandingPrincipalBalance,
        'paymentAmount': value.paymentAmount,
        'paymentDate': value.paymentDate,
        'originationDate': value.originationDate,
        'originationPrincipalAmount': value.originationPrincipalAmount,
        'pastDueAmount': value.pastDueAmount,
        'ytdInterestPaid': value.ytdInterestPaid,
        'ytdPrincipalPaid': value.ytdPrincipalPaid,
        'propertyAddressCity': value.propertyAddressCity,
        'propertyAddressState': value.propertyAddressState,
        'propertyAddressStreet': value.propertyAddressStreet,
        'propertyAddressPostalCode': value.propertyAddressPostalCode,
        'propertyRegion': value.propertyRegion,
        'propertyCountry': value.propertyCountry,
        'interestRatePercentage': value.interestRatePercentage,
        'interestRateType': value.interestRateType,
        'status': BankAccountStatusToJSON(value.status),
    };
}

