/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PersonalActionableInsightName } from './PersonalActionableInsightName';
import {
    PersonalActionableInsightNameFromJSON,
    PersonalActionableInsightNameFromJSONTyped,
    PersonalActionableInsightNameToJSON,
} from './PersonalActionableInsightName';

/**
 * 
 * @export
 * @interface PersonalActionableInsight
 */
export interface PersonalActionableInsight {
    /**
     * 
     * @type {string}
     * @memberof PersonalActionableInsight
     */
    id?: string;
    /**
     * 
     * @type {PersonalActionableInsightName}
     * @memberof PersonalActionableInsight
     */
    insightName?: PersonalActionableInsightName;
    /**
     * 
     * @type {string}
     * @memberof PersonalActionableInsight
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalActionableInsight
     */
    takeaway?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalActionableInsight
     */
    action?: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalActionableInsight
     */
    expectedBenefit?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PersonalActionableInsight
     */
    tags?: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof PersonalActionableInsight
     */
    generatedTime?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof PersonalActionableInsight
     */
    metricsToOptimizeFor?: Array<string>;
}

/**
 * Check if a given object implements the PersonalActionableInsight interface.
 */
export function instanceOfPersonalActionableInsight(value: object): boolean {
    return true;
}

export function PersonalActionableInsightFromJSON(json: any): PersonalActionableInsight {
    return PersonalActionableInsightFromJSONTyped(json, false);
}

export function PersonalActionableInsightFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalActionableInsight {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'insightName': json['insightName'] == null ? undefined : PersonalActionableInsightNameFromJSON(json['insightName']),
        'description': json['description'] == null ? undefined : json['description'],
        'takeaway': json['takeaway'] == null ? undefined : json['takeaway'],
        'action': json['action'] == null ? undefined : json['action'],
        'expectedBenefit': json['expectedBenefit'] == null ? undefined : json['expectedBenefit'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'generatedTime': json['generatedTime'] == null ? undefined : (new Date(json['generatedTime'])),
        'metricsToOptimizeFor': json['metricsToOptimizeFor'] == null ? undefined : json['metricsToOptimizeFor'],
    };
}

export function PersonalActionableInsightToJSON(value?: PersonalActionableInsight | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'insightName': PersonalActionableInsightNameToJSON(value['insightName']),
        'description': value['description'],
        'takeaway': value['takeaway'],
        'action': value['action'],
        'expectedBenefit': value['expectedBenefit'],
        'tags': value['tags'],
        'generatedTime': value['generatedTime'] == null ? undefined : ((value['generatedTime']).toISOString()),
        'metricsToOptimizeFor': value['metricsToOptimizeFor'],
    };
}

