/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaidLink
 */
export interface PlaidLink {
    /**
     * 
     * @type {string}
     * @memberof PlaidLink
     */
    id?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlaidLink
     */
    products?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof PlaidLink
     */
    webhookUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidLink
     */
    institutionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidLink
     */
    institutionName?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlaidLink
     */
    usePlaidSync?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PlaidLink
     */
    itemId?: string;
}

/**
 * Check if a given object implements the PlaidLink interface.
 */
export function instanceOfPlaidLink(value: object): boolean {
    return true;
}

export function PlaidLinkFromJSON(json: any): PlaidLink {
    return PlaidLinkFromJSONTyped(json, false);
}

export function PlaidLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidLink {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'products': json['products'] == null ? undefined : json['products'],
        'webhookUrl': json['webhookUrl'] == null ? undefined : json['webhookUrl'],
        'institutionId': json['institutionId'] == null ? undefined : json['institutionId'],
        'institutionName': json['institutionName'] == null ? undefined : json['institutionName'],
        'usePlaidSync': json['usePlaidSync'] == null ? undefined : json['usePlaidSync'],
        'itemId': json['itemId'] == null ? undefined : json['itemId'],
    };
}

export function PlaidLinkToJSON(value?: PlaidLink | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'products': value['products'],
        'webhookUrl': value['webhookUrl'],
        'institutionId': value['institutionId'],
        'institutionName': value['institutionName'],
        'usePlaidSync': value['usePlaidSync'],
        'itemId': value['itemId'],
    };
}

