/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FinancialUserProfileType } from './FinancialUserProfileType';
import {
    FinancialUserProfileTypeFromJSON,
    FinancialUserProfileTypeFromJSONTyped,
    FinancialUserProfileTypeToJSON,
} from './FinancialUserProfileType';

/**
 * 
 * @export
 * @interface PlaidInitiateTokenUpdateRequest
 */
export interface PlaidInitiateTokenUpdateRequest {
    /**
     * 
     * @type {string}
     * @memberof PlaidInitiateTokenUpdateRequest
     */
    userId: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidInitiateTokenUpdateRequest
     */
    linkId: string;
    /**
     * 
     * @type {FinancialUserProfileType}
     * @memberof PlaidInitiateTokenUpdateRequest
     */
    profileType: FinancialUserProfileType;
}

/**
 * Check if a given object implements the PlaidInitiateTokenUpdateRequest interface.
 */
export function instanceOfPlaidInitiateTokenUpdateRequest(value: object): boolean {
    if (!('userId' in value)) return false;
    if (!('linkId' in value)) return false;
    if (!('profileType' in value)) return false;
    return true;
}

export function PlaidInitiateTokenUpdateRequestFromJSON(json: any): PlaidInitiateTokenUpdateRequest {
    return PlaidInitiateTokenUpdateRequestFromJSONTyped(json, false);
}

export function PlaidInitiateTokenUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidInitiateTokenUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'],
        'linkId': json['linkId'],
        'profileType': FinancialUserProfileTypeFromJSON(json['profileType']),
    };
}

export function PlaidInitiateTokenUpdateRequestToJSON(value?: PlaidInitiateTokenUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userId': value['userId'],
        'linkId': value['linkId'],
        'profileType': FinancialUserProfileTypeToJSON(value['profileType']),
    };
}

