/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Any1 } from './Any1';
import {
    Any1FromJSON,
    Any1FromJSONTyped,
    Any1ToJSON,
} from './Any1';
import type { SmartNote } from './SmartNote';
import {
    SmartNoteFromJSON,
    SmartNoteFromJSONTyped,
    SmartNoteToJSON,
} from './SmartNote';

/**
 * Message representing investment transactions associated with a Plaid account.
 * @export
 * @interface PlaidAccountInvestmentTransaction
 */
export interface PlaidAccountInvestmentTransaction {
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    accountId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    ammount?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    investmentTransactionId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    securityId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    currentDate?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof PlaidAccountInvestmentTransaction
     */
    quantity?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaidAccountInvestmentTransaction
     */
    amount?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaidAccountInvestmentTransaction
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof PlaidAccountInvestmentTransaction
     */
    fees?: number;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    subtype?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    isoCurrencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    unofficialCurrencyCode?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    linkId?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof PlaidAccountInvestmentTransaction
     */
    userId?: string;
    /**
     * 
     * @type {Date}
     * @memberof PlaidAccountInvestmentTransaction
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PlaidAccountInvestmentTransaction
     */
    time?: Date;
    /**
     * 
     * @type {Any1}
     * @memberof PlaidAccountInvestmentTransaction
     */
    additionalProperties?: Any1;
    /**
     * 
     * @type {Array<SmartNote>}
     * @memberof PlaidAccountInvestmentTransaction
     */
    notes?: Array<SmartNote>;
}

/**
 * Check if a given object implements the PlaidAccountInvestmentTransaction interface.
 */
export function instanceOfPlaidAccountInvestmentTransaction(value: object): boolean {
    return true;
}

export function PlaidAccountInvestmentTransactionFromJSON(json: any): PlaidAccountInvestmentTransaction {
    return PlaidAccountInvestmentTransactionFromJSONTyped(json, false);
}

export function PlaidAccountInvestmentTransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaidAccountInvestmentTransaction {
    if (json == null) {
        return json;
    }
    return {
        
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'ammount': json['ammount'] == null ? undefined : json['ammount'],
        'investmentTransactionId': json['investmentTransactionId'] == null ? undefined : json['investmentTransactionId'],
        'securityId': json['securityId'] == null ? undefined : json['securityId'],
        'currentDate': json['currentDate'] == null ? undefined : json['currentDate'],
        'name': json['name'] == null ? undefined : json['name'],
        'quantity': json['quantity'] == null ? undefined : json['quantity'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'price': json['price'] == null ? undefined : json['price'],
        'fees': json['fees'] == null ? undefined : json['fees'],
        'type': json['type'] == null ? undefined : json['type'],
        'subtype': json['subtype'] == null ? undefined : json['subtype'],
        'isoCurrencyCode': json['isoCurrencyCode'] == null ? undefined : json['isoCurrencyCode'],
        'unofficialCurrencyCode': json['unofficialCurrencyCode'] == null ? undefined : json['unofficialCurrencyCode'],
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'time': json['time'] == null ? undefined : (new Date(json['time'])),
        'additionalProperties': json['additionalProperties'] == null ? undefined : Any1FromJSON(json['additionalProperties']),
        'notes': json['notes'] == null ? undefined : ((json['notes'] as Array<any>).map(SmartNoteFromJSON)),
    };
}

export function PlaidAccountInvestmentTransactionToJSON(value?: PlaidAccountInvestmentTransaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accountId': value['accountId'],
        'ammount': value['ammount'],
        'investmentTransactionId': value['investmentTransactionId'],
        'securityId': value['securityId'],
        'currentDate': value['currentDate'],
        'name': value['name'],
        'quantity': value['quantity'],
        'amount': value['amount'],
        'price': value['price'],
        'fees': value['fees'],
        'type': value['type'],
        'subtype': value['subtype'],
        'isoCurrencyCode': value['isoCurrencyCode'],
        'unofficialCurrencyCode': value['unofficialCurrencyCode'],
        'linkId': value['linkId'],
        'id': value['id'],
        'userId': value['userId'],
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'time': value['time'] == null ? undefined : ((value['time']).toISOString()),
        'additionalProperties': Any1ToJSON(value['additionalProperties']),
        'notes': value['notes'] == null ? undefined : ((value['notes'] as Array<any>).map(SmartNoteToJSON)),
    };
}

