/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
} from './Comment';

/**
 * 
 * @export
 * @interface ReactToCommentResponse
 */
export interface ReactToCommentResponse {
    /**
     * 
     * @type {Comment}
     * @memberof ReactToCommentResponse
     */
    comment?: Comment;
}

/**
 * Check if a given object implements the ReactToCommentResponse interface.
 */
export function instanceOfReactToCommentResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReactToCommentResponseFromJSON(json: any): ReactToCommentResponse {
    return ReactToCommentResponseFromJSONTyped(json, false);
}

export function ReactToCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReactToCommentResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'comment': !exists(json, 'comment') ? undefined : CommentFromJSON(json['comment']),
    };
}

export function ReactToCommentResponseToJSON(value?: ReactToCommentResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'comment': CommentToJSON(value.comment),
    };
}

