/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { IncomeStatement } from './IncomeStatement';
import {
    IncomeStatementFromJSON,
    IncomeStatementFromJSONTyped,
    IncomeStatementToJSON,
} from './IncomeStatement';

/**
 * 
 * @export
 * @interface ReadIncomeStatementsResponse
 */
export interface ReadIncomeStatementsResponse {
    /**
     * 
     * @type {Array<IncomeStatement>}
     * @memberof ReadIncomeStatementsResponse
     */
    incomeStatements?: Array<IncomeStatement>;
    /**
     * 
     * @type {number}
     * @memberof ReadIncomeStatementsResponse
     */
    nextPage?: number;
}

/**
 * Check if a given object implements the ReadIncomeStatementsResponse interface.
 */
export function instanceOfReadIncomeStatementsResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ReadIncomeStatementsResponseFromJSON(json: any): ReadIncomeStatementsResponse {
    return ReadIncomeStatementsResponseFromJSONTyped(json, false);
}

export function ReadIncomeStatementsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadIncomeStatementsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'incomeStatements': !exists(json, 'incomeStatements') ? undefined : ((json['incomeStatements'] as Array<any>).map(IncomeStatementFromJSON)),
        'nextPage': !exists(json, 'nextPage') ? undefined : json['nextPage'],
    };
}

export function ReadIncomeStatementsResponseToJSON(value?: ReadIncomeStatementsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'incomeStatements': value.incomeStatements === undefined ? undefined : ((value.incomeStatements as Array<any>).map(IncomeStatementToJSON)),
        'nextPage': value.nextPage,
    };
}

