/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadCashFlowStatementsRequest
 */
export interface ReadCashFlowStatementsRequest {
    /**
     * 
     * @type {string}
     * @memberof ReadCashFlowStatementsRequest
     */
    authZeroUserId: string;
    /**
     * 
     * @type {string}
     * @memberof ReadCashFlowStatementsRequest
     */
    acountingIntegrationMergeLinkId: string;
    /**
     * 
     * @type {Date}
     * @memberof ReadCashFlowStatementsRequest
     */
    startDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof ReadCashFlowStatementsRequest
     */
    endDate: Date;
    /**
     * 
     * @type {number}
     * @memberof ReadCashFlowStatementsRequest
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof ReadCashFlowStatementsRequest
     */
    pageNumber: number;
}

/**
 * Check if a given object implements the ReadCashFlowStatementsRequest interface.
 */
export function instanceOfReadCashFlowStatementsRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "authZeroUserId" in value;
    isInstance = isInstance && "acountingIntegrationMergeLinkId" in value;
    isInstance = isInstance && "startDate" in value;
    isInstance = isInstance && "endDate" in value;
    isInstance = isInstance && "pageSize" in value;
    isInstance = isInstance && "pageNumber" in value;

    return isInstance;
}

export function ReadCashFlowStatementsRequestFromJSON(json: any): ReadCashFlowStatementsRequest {
    return ReadCashFlowStatementsRequestFromJSONTyped(json, false);
}

export function ReadCashFlowStatementsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadCashFlowStatementsRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'authZeroUserId': json['authZeroUserId'],
        'acountingIntegrationMergeLinkId': json['acountingIntegrationMergeLinkId'],
        'startDate': (new Date(json['startDate'])),
        'endDate': (new Date(json['endDate'])),
        'pageSize': json['pageSize'],
        'pageNumber': json['pageNumber'],
    };
}

export function ReadCashFlowStatementsRequestToJSON(value?: ReadCashFlowStatementsRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'authZeroUserId': value.authZeroUserId,
        'acountingIntegrationMergeLinkId': value.acountingIntegrationMergeLinkId,
        'startDate': (value.startDate.toISOString()),
        'endDate': (value.endDate.toISOString()),
        'pageSize': value.pageSize,
        'pageNumber': value.pageNumber,
    };
}

