/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RemovePostFromThreadResponse
 */
export interface RemovePostFromThreadResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RemovePostFromThreadResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the RemovePostFromThreadResponse interface.
 */
export function instanceOfRemovePostFromThreadResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function RemovePostFromThreadResponseFromJSON(json: any): RemovePostFromThreadResponse {
    return RemovePostFromThreadResponseFromJSONTyped(json, false);
}

export function RemovePostFromThreadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemovePostFromThreadResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function RemovePostFromThreadResponseToJSON(value?: RemovePostFromThreadResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

