/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Comment } from './Comment';
import {
    CommentFromJSON,
    CommentFromJSONTyped,
    CommentToJSON,
} from './Comment';

/**
 * 
 * @export
 * @interface ReportCommentResponse
 */
export interface ReportCommentResponse {
    /**
     * 
     * @type {Comment}
     * @memberof ReportCommentResponse
     */
    comment?: Comment;
}

/**
 * Check if a given object implements the ReportCommentResponse interface.
 */
export function instanceOfReportCommentResponse(value: object): boolean {
    return true;
}

export function ReportCommentResponseFromJSON(json: any): ReportCommentResponse {
    return ReportCommentResponseFromJSONTyped(json, false);
}

export function ReportCommentResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportCommentResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'comment': json['comment'] == null ? undefined : CommentFromJSON(json['comment']),
    };
}

export function ReportCommentResponseToJSON(value?: ReportCommentResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'comment': CommentToJSON(value['comment']),
    };
}

