/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * RoleType defines the different types of roles.
 * @export
 */
export const RoleType = {
    Unspecified: 'ROLE_TYPE_UNSPECIFIED',
    SuperAdmin: 'ROLE_TYPE_SUPER_ADMIN',
    TeamAdmin: 'ROLE_TYPE_TEAM_ADMIN',
    Regular: 'ROLE_TYPE_REGULAR'
} as const;
export type RoleType = typeof RoleType[keyof typeof RoleType];


export function RoleTypeFromJSON(json: any): RoleType {
    return RoleTypeFromJSONTyped(json, false);
}

export function RoleTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleType {
    return json as RoleType;
}

export function RoleTypeToJSON(value?: RoleType | null): any {
    return value as any;
}

