/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlaidAccountTransaction } from './PlaidAccountTransaction';
import {
    PlaidAccountTransactionFromJSON,
    PlaidAccountTransactionFromJSONTyped,
    PlaidAccountTransactionToJSON,
} from './PlaidAccountTransaction';

/**
 * 
 * @export
 * @interface SearchTransactionsResponse
 */
export interface SearchTransactionsResponse {
    /**
     * 
     * @type {Array<PlaidAccountTransaction>}
     * @memberof SearchTransactionsResponse
     */
    transactions?: Array<PlaidAccountTransaction>;
    /**
     * 
     * @type {string}
     * @memberof SearchTransactionsResponse
     */
    nextPageNumber?: string;
}

/**
 * Check if a given object implements the SearchTransactionsResponse interface.
 */
export function instanceOfSearchTransactionsResponse(value: object): boolean {
    return true;
}

export function SearchTransactionsResponseFromJSON(json: any): SearchTransactionsResponse {
    return SearchTransactionsResponseFromJSONTyped(json, false);
}

export function SearchTransactionsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchTransactionsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(PlaidAccountTransactionFromJSON)),
        'nextPageNumber': json['nextPageNumber'] == null ? undefined : json['nextPageNumber'],
    };
}

export function SearchTransactionsResponseToJSON(value?: SearchTransactionsResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(PlaidAccountTransactionToJSON)),
        'nextPageNumber': value['nextPageNumber'],
    };
}

