/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SharePostResponse
 */
export interface SharePostResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SharePostResponse
     */
    success?: boolean;
}

/**
 * Check if a given object implements the SharePostResponse interface.
 */
export function instanceOfSharePostResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function SharePostResponseFromJSON(json: any): SharePostResponse {
    return SharePostResponseFromJSONTyped(json, false);
}

export function SharePostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SharePostResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': !exists(json, 'success') ? undefined : json['success'],
    };
}

export function SharePostResponseToJSON(value?: SharePostResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

