/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Tags
 */
export interface Tags {
    /**
     * 
     * @type {string}
     * @memberof Tags
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Tags
     */
    tagName?: string;
    /**
     * 
     * @type {string}
     * @memberof Tags
     */
    tagDescription?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Tags
     */
    metadata?: Array<string>;
}

/**
 * Check if a given object implements the Tags interface.
 */
export function instanceOfTags(value: object): boolean {
    return true;
}

export function TagsFromJSON(json: any): Tags {
    return TagsFromJSONTyped(json, false);
}

export function TagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Tags {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'tagName': json['tagName'] == null ? undefined : json['tagName'],
        'tagDescription': json['tagDescription'] == null ? undefined : json['tagDescription'],
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function TagsToJSON(value?: Tags | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'tagName': value['tagName'],
        'tagDescription': value['tagDescription'],
        'metadata': value['metadata'],
    };
}

