/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BusinessAccount } from './BusinessAccount';
import {
    BusinessAccountFromJSON,
    BusinessAccountFromJSONTyped,
    BusinessAccountToJSON,
} from './BusinessAccount';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
} from './Role';
import type { Tags } from './Tags';
import {
    TagsFromJSON,
    TagsFromJSONTyped,
    TagsToJSON,
} from './Tags';
import type { UserAccount } from './UserAccount';
import {
    UserAccountFromJSON,
    UserAccountFromJSONTyped,
    UserAccountToJSON,
} from './UserAccount';

/**
 * Team: represents a team within the context of solomon-ai.
 * @export
 * @interface Team
 */
export interface Team {
    /**
     * Unique identifier for the team.
     * @type {string}
     * @memberof Team
     */
    id?: string;
    /**
     * Name of the team.
     * @type {string}
     * @memberof Team
     */
    name?: string;
    /**
     * Description of the team.
     * @type {string}
     * @memberof Team
     */
    description?: string;
    /**
     * Tags associated with the team.
     * @type {Array<Tags>}
     * @memberof Team
     */
    tags?: Array<Tags>;
    /**
     * 
     * @type {BusinessAccount}
     * @memberof Team
     */
    teamAdmin?: BusinessAccount;
    /**
     * Members of the team.
     * @type {Array<UserAccount>}
     * @memberof Team
     */
    memberUsersAccounts?: Array<UserAccount>;
    /**
     * Member business accounts of the team.
     * @type {Array<BusinessAccount>}
     * @memberof Team
     */
    memberBusinessAccounts?: Array<BusinessAccount>;
    /**
     * Timestamp for when the team was created.
     * @type {Date}
     * @memberof Team
     */
    createdAt?: Date;
    /**
     * Timestamp for when the team was last updated.
     * @type {Date}
     * @memberof Team
     */
    updatedAt?: Date;
    /**
     * 
     * @type {Array<Role>}
     * @memberof Team
     */
    roles?: Array<Role>;
}

/**
 * Check if a given object implements the Team interface.
 */
export function instanceOfTeam(value: object): boolean {
    return true;
}

export function TeamFromJSON(json: any): Team {
    return TeamFromJSONTyped(json, false);
}

export function TeamFromJSONTyped(json: any, ignoreDiscriminator: boolean): Team {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagsFromJSON)),
        'teamAdmin': json['teamAdmin'] == null ? undefined : BusinessAccountFromJSON(json['teamAdmin']),
        'memberUsersAccounts': json['memberUsersAccounts'] == null ? undefined : ((json['memberUsersAccounts'] as Array<any>).map(UserAccountFromJSON)),
        'memberBusinessAccounts': json['memberBusinessAccounts'] == null ? undefined : ((json['memberBusinessAccounts'] as Array<any>).map(BusinessAccountFromJSON)),
        'createdAt': json['createdAt'] == null ? undefined : (new Date(json['createdAt'])),
        'updatedAt': json['updatedAt'] == null ? undefined : (new Date(json['updatedAt'])),
        'roles': json['roles'] == null ? undefined : ((json['roles'] as Array<any>).map(RoleFromJSON)),
    };
}

export function TeamToJSON(value?: Team | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagsToJSON)),
        'teamAdmin': BusinessAccountToJSON(value['teamAdmin']),
        'memberUsersAccounts': value['memberUsersAccounts'] == null ? undefined : ((value['memberUsersAccounts'] as Array<any>).map(UserAccountToJSON)),
        'memberBusinessAccounts': value['memberBusinessAccounts'] == null ? undefined : ((value['memberBusinessAccounts'] as Array<any>).map(BusinessAccountToJSON)),
        'createdAt': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
        'updatedAt': value['updatedAt'] == null ? undefined : ((value['updatedAt']).toISOString()),
        'roles': value['roles'] == null ? undefined : ((value['roles'] as Array<any>).map(RoleToJSON)),
    };
}

