/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FinancialAccountType } from './FinancialAccountType';
import {
    FinancialAccountTypeFromJSON,
    FinancialAccountTypeFromJSONTyped,
    FinancialAccountTypeToJSON,
} from './FinancialAccountType';
import type { FinancialUserProfileType } from './FinancialUserProfileType';
import {
    FinancialUserProfileTypeFromJSON,
    FinancialUserProfileTypeFromJSONTyped,
    FinancialUserProfileTypeToJSON,
} from './FinancialUserProfileType';

/**
 * 
 * @export
 * @interface TriggerSyncRequest
 */
export interface TriggerSyncRequest {
    /**
     * 
     * @type {string}
     * @memberof TriggerSyncRequest
     */
    userId?: string;
    /**
     * 
     * @type {FinancialUserProfileType}
     * @memberof TriggerSyncRequest
     */
    profileType: FinancialUserProfileType;
    /**
     * 
     * @type {string}
     * @memberof TriggerSyncRequest
     */
    linkId?: string;
    /**
     * 
     * @type {FinancialAccountType}
     * @memberof TriggerSyncRequest
     */
    financialAccountType: FinancialAccountType;
}

/**
 * Check if a given object implements the TriggerSyncRequest interface.
 */
export function instanceOfTriggerSyncRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "profileType" in value;
    isInstance = isInstance && "financialAccountType" in value;

    return isInstance;
}

export function TriggerSyncRequestFromJSON(json: any): TriggerSyncRequest {
    return TriggerSyncRequestFromJSONTyped(json, false);
}

export function TriggerSyncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerSyncRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'profileType': FinancialUserProfileTypeFromJSON(json['profileType']),
        'linkId': !exists(json, 'linkId') ? undefined : json['linkId'],
        'financialAccountType': FinancialAccountTypeFromJSON(json['financialAccountType']),
    };
}

export function TriggerSyncRequestToJSON(value?: TriggerSyncRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userId': value.userId,
        'profileType': FinancialUserProfileTypeToJSON(value.profileType),
        'linkId': value.linkId,
        'financialAccountType': FinancialAccountTypeToJSON(value.financialAccountType),
    };
}

