/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileMetadata } from './FileMetadata';
import {
    FileMetadataFromJSON,
    FileMetadataFromJSONTyped,
    FileMetadataToJSON,
} from './FileMetadata';

/**
 * 
 * @export
 * @interface UpdateFileRequest
 */
export interface UpdateFileRequest {
    /**
     * 
     * @type {FileMetadata}
     * @memberof UpdateFileRequest
     */
    metadata?: FileMetadata;
}

/**
 * Check if a given object implements the UpdateFileRequest interface.
 */
export function instanceOfUpdateFileRequest(value: object): boolean {
    return true;
}

export function UpdateFileRequestFromJSON(json: any): UpdateFileRequest {
    return UpdateFileRequestFromJSONTyped(json, false);
}

export function UpdateFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': json['metadata'] == null ? undefined : FileMetadataFromJSON(json['metadata']),
    };
}

export function UpdateFileRequestToJSON(value?: UpdateFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'metadata': FileMetadataToJSON(value['metadata']),
    };
}

