/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BankAccount } from './BankAccount';
import {
    BankAccountFromJSON,
    BankAccountFromJSONTyped,
    BankAccountToJSON,
} from './BankAccount';

/**
 * 
 * @export
 * @interface UpdateBankAccountResponse
 */
export interface UpdateBankAccountResponse {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateBankAccountResponse
     */
    updated?: boolean;
    /**
     * 
     * @type {BankAccount}
     * @memberof UpdateBankAccountResponse
     */
    bankAccount?: BankAccount;
}

/**
 * Check if a given object implements the UpdateBankAccountResponse interface.
 */
export function instanceOfUpdateBankAccountResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateBankAccountResponseFromJSON(json: any): UpdateBankAccountResponse {
    return UpdateBankAccountResponseFromJSONTyped(json, false);
}

export function UpdateBankAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBankAccountResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updated': !exists(json, 'updated') ? undefined : json['updated'],
        'bankAccount': !exists(json, 'bankAccount') ? undefined : BankAccountFromJSON(json['bankAccount']),
    };
}

export function UpdateBankAccountResponseToJSON(value?: UpdateBankAccountResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updated': value.updated,
        'bankAccount': BankAccountToJSON(value.bankAccount),
    };
}

