/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BankAccount } from './BankAccount';
import {
    BankAccountFromJSON,
    BankAccountFromJSONTyped,
    BankAccountToJSON,
} from './BankAccount';

/**
 * 
 * @export
 * @interface UpdateBankAccountRequest
 */
export interface UpdateBankAccountRequest {
    /**
     * 
     * @type {BankAccount}
     * @memberof UpdateBankAccountRequest
     */
    bankAccount: BankAccount;
}

/**
 * Check if a given object implements the UpdateBankAccountRequest interface.
 */
export function instanceOfUpdateBankAccountRequest(value: object): boolean {
    if (!('bankAccount' in value)) return false;
    return true;
}

export function UpdateBankAccountRequestFromJSON(json: any): UpdateBankAccountRequest {
    return UpdateBankAccountRequestFromJSONTyped(json, false);
}

export function UpdateBankAccountRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBankAccountRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'bankAccount': BankAccountFromJSON(json['bankAccount']),
    };
}

export function UpdateBankAccountRequestToJSON(value?: UpdateBankAccountRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'bankAccount': BankAccountToJSON(value['bankAccount']),
    };
}

