/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Role } from './Role';
import {
    RoleFromJSON,
    RoleFromJSONTyped,
    RoleToJSON,
} from './Role';

/**
 * 
 * @export
 * @interface UpdateRoleResponse
 */
export interface UpdateRoleResponse {
    /**
     * 
     * @type {Role}
     * @memberof UpdateRoleResponse
     */
    role?: Role;
}

/**
 * Check if a given object implements the UpdateRoleResponse interface.
 */
export function instanceOfUpdateRoleResponse(value: object): boolean {
    return true;
}

export function UpdateRoleResponseFromJSON(json: any): UpdateRoleResponse {
    return UpdateRoleResponseFromJSONTyped(json, false);
}

export function UpdateRoleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateRoleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'role': json['role'] == null ? undefined : RoleFromJSON(json['role']),
    };
}

export function UpdateRoleResponseToJSON(value?: UpdateRoleResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'role': RoleToJSON(value['role']),
    };
}

