/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BusinessAccount } from './BusinessAccount';
import {
    BusinessAccountFromJSON,
    BusinessAccountFromJSONTyped,
    BusinessAccountToJSON,
} from './BusinessAccount';
import type { UserAccount } from './UserAccount';
import {
    UserAccountFromJSON,
    UserAccountFromJSONTyped,
    UserAccountToJSON,
} from './UserAccount';

/**
 * 
 * @export
 * @interface UpdateUserV2Request
 */
export interface UpdateUserV2Request {
    /**
     * 
     * @type {UserAccount}
     * @memberof UpdateUserV2Request
     */
    userAccount?: UserAccount;
    /**
     * 
     * @type {BusinessAccount}
     * @memberof UpdateUserV2Request
     */
    businessAccount?: BusinessAccount;
}

/**
 * Check if a given object implements the UpdateUserV2Request interface.
 */
export function instanceOfUpdateUserV2Request(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserV2RequestFromJSON(json: any): UpdateUserV2Request {
    return UpdateUserV2RequestFromJSONTyped(json, false);
}

export function UpdateUserV2RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserV2Request {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userAccount': !exists(json, 'userAccount') ? undefined : UserAccountFromJSON(json['userAccount']),
        'businessAccount': !exists(json, 'businessAccount') ? undefined : BusinessAccountFromJSON(json['businessAccount']),
    };
}

export function UpdateUserV2RequestToJSON(value?: UpdateUserV2Request | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'userAccount': UserAccountToJSON(value.userAccount),
        'businessAccount': BusinessAccountToJSON(value.businessAccount),
    };
}

