/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { UserAccount } from './UserAccount';
import {
    UserAccountFromJSON,
    UserAccountFromJSONTyped,
    UserAccountToJSON,
} from './UserAccount';

/**
 * 
 * @export
 * @interface UpdateUserResponse
 */
export interface UpdateUserResponse {
    /**
     * 
     * @type {boolean}
     * @memberof UpdateUserResponse
     */
    accountUpdated?: boolean;
    /**
     * 
     * @type {UserAccount}
     * @memberof UpdateUserResponse
     */
    account?: UserAccount;
}

/**
 * Check if a given object implements the UpdateUserResponse interface.
 */
export function instanceOfUpdateUserResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateUserResponseFromJSON(json: any): UpdateUserResponse {
    return UpdateUserResponseFromJSONTyped(json, false);
}

export function UpdateUserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateUserResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'accountUpdated': !exists(json, 'accountUpdated') ? undefined : json['accountUpdated'],
        'account': !exists(json, 'account') ? undefined : UserAccountFromJSON(json['account']),
    };
}

export function UpdateUserResponseToJSON(value?: UpdateUserResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'accountUpdated': value.accountUpdated,
        'account': UserAccountToJSON(value.account),
    };
}

