/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SmartNote } from './SmartNote';
import {
    SmartNoteFromJSON,
    SmartNoteFromJSONTyped,
    SmartNoteToJSON,
} from './SmartNote';

/**
 * 
 * @export
 * @interface UpdateNoteToTransactionRequest
 */
export interface UpdateNoteToTransactionRequest {
    /**
     * 
     * @type {SmartNote}
     * @memberof UpdateNoteToTransactionRequest
     */
    note: SmartNote;
}

/**
 * Check if a given object implements the UpdateNoteToTransactionRequest interface.
 */
export function instanceOfUpdateNoteToTransactionRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "note" in value;

    return isInstance;
}

export function UpdateNoteToTransactionRequestFromJSON(json: any): UpdateNoteToTransactionRequest {
    return UpdateNoteToTransactionRequestFromJSONTyped(json, false);
}

export function UpdateNoteToTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateNoteToTransactionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'note': SmartNoteFromJSON(json['note']),
    };
}

export function UpdateNoteToTransactionRequestToJSON(value?: UpdateNoteToTransactionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'note': SmartNoteToJSON(value.note),
    };
}

