/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Budget } from './Budget';
import {
    BudgetFromJSON,
    BudgetFromJSONTyped,
    BudgetToJSON,
} from './Budget';

/**
 * 
 * @export
 * @interface UpdateBudgetRequest
 */
export interface UpdateBudgetRequest {
    /**
     * 
     * @type {Budget}
     * @memberof UpdateBudgetRequest
     */
    budget: Budget;
}

/**
 * Check if a given object implements the UpdateBudgetRequest interface.
 */
export function instanceOfUpdateBudgetRequest(value: object): boolean {
    if (!('budget' in value)) return false;
    return true;
}

export function UpdateBudgetRequestFromJSON(json: any): UpdateBudgetRequest {
    return UpdateBudgetRequestFromJSONTyped(json, false);
}

export function UpdateBudgetRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateBudgetRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'budget': BudgetFromJSON(json['budget']),
    };
}

export function UpdateBudgetRequestToJSON(value?: UpdateBudgetRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'budget': BudgetToJSON(value['budget']),
    };
}

