/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MergeBusinessProfile } from './MergeBusinessProfile';
import {
    MergeBusinessProfileFromJSON,
    MergeBusinessProfileFromJSONTyped,
    MergeBusinessProfileToJSON,
} from './MergeBusinessProfile';

/**
 * Defines a message named UpdateAccountingProfileRequest.
 * @export
 * @interface UpdateAccountingProfileRequest
 */
export interface UpdateAccountingProfileRequest {
    /**
     * 
     * @type {MergeBusinessProfile}
     * @memberof UpdateAccountingProfileRequest
     */
    profile?: MergeBusinessProfile;
}

/**
 * Check if a given object implements the UpdateAccountingProfileRequest interface.
 */
export function instanceOfUpdateAccountingProfileRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateAccountingProfileRequestFromJSON(json: any): UpdateAccountingProfileRequest {
    return UpdateAccountingProfileRequestFromJSONTyped(json, false);
}

export function UpdateAccountingProfileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateAccountingProfileRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profile': !exists(json, 'profile') ? undefined : MergeBusinessProfileFromJSON(json['profile']),
    };
}

export function UpdateAccountingProfileRequestToJSON(value?: UpdateAccountingProfileRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profile': MergeBusinessProfileToJSON(value.profile),
    };
}

