/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Milestone } from './Milestone';
import {
    MilestoneFromJSON,
    MilestoneFromJSONTyped,
    MilestoneToJSON,
} from './Milestone';

/**
 * 
 * @export
 * @interface UpdateMilestoneRequest
 */
export interface UpdateMilestoneRequest {
    /**
     * 
     * @type {Milestone}
     * @memberof UpdateMilestoneRequest
     */
    milestone: Milestone;
}

/**
 * Check if a given object implements the UpdateMilestoneRequest interface.
 */
export function instanceOfUpdateMilestoneRequest(value: object): boolean {
    if (!('milestone' in value)) return false;
    return true;
}

export function UpdateMilestoneRequestFromJSON(json: any): UpdateMilestoneRequest {
    return UpdateMilestoneRequestFromJSONTyped(json, false);
}

export function UpdateMilestoneRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMilestoneRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'milestone': MilestoneFromJSON(json['milestone']),
    };
}

export function UpdateMilestoneRequestToJSON(value?: UpdateMilestoneRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'milestone': MilestoneToJSON(value['milestone']),
    };
}

