/* tslint:disable */
/* eslint-disable */
/**
 * User Service
 * Solomon AI User Service API
 *
 * The version of the OpenAPI document: 0.1
 * Contact: yoanyomba@solomon-ai.co
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VendorCreditLine } from './VendorCreditLine';
import {
    VendorCreditLineFromJSON,
    VendorCreditLineFromJSONTyped,
    VendorCreditLineToJSON,
} from './VendorCreditLine';

/**
 * The VendorCredit object represents an accounts receivable transaction indicating that a customer is owed a gift or refund. 
 * It includes details such as the amount of credit, the vendor responsible, 
 * the associated account, and other relevant information.
 * @export
 * @interface VendorCredit
 */
export interface VendorCredit {
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    mergeRecordId?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    remoteId?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    number?: string;
    /**
     * 
     * @type {Date}
     * @memberof VendorCredit
     */
    transactionDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    vendor?: string;
    /**
     * 
     * @type {number}
     * @memberof VendorCredit
     */
    totalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    currency?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    exchangeRate?: string;
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    company?: string;
    /**
     * 
     * @type {Array<VendorCreditLine>}
     * @memberof VendorCredit
     */
    lines?: Array<VendorCreditLine>;
    /**
     * 
     * @type {Array<string>}
     * @memberof VendorCredit
     */
    trackingCategories?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof VendorCredit
     */
    remoteWasDeleted?: boolean;
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    accountingPeriod?: string;
    /**
     * 
     * @type {Date}
     * @memberof VendorCredit
     */
    modifiedAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof VendorCredit
     */
    id?: string;
}

/**
 * Check if a given object implements the VendorCredit interface.
 */
export function instanceOfVendorCredit(value: object): boolean {
    return true;
}

export function VendorCreditFromJSON(json: any): VendorCredit {
    return VendorCreditFromJSONTyped(json, false);
}

export function VendorCreditFromJSONTyped(json: any, ignoreDiscriminator: boolean): VendorCredit {
    if (json == null) {
        return json;
    }
    return {
        
        'mergeRecordId': json['mergeRecordId'] == null ? undefined : json['mergeRecordId'],
        'remoteId': json['remoteId'] == null ? undefined : json['remoteId'],
        'number': json['number'] == null ? undefined : json['number'],
        'transactionDate': json['transactionDate'] == null ? undefined : (new Date(json['transactionDate'])),
        'vendor': json['vendor'] == null ? undefined : json['vendor'],
        'totalAmount': json['totalAmount'] == null ? undefined : json['totalAmount'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'exchangeRate': json['exchangeRate'] == null ? undefined : json['exchangeRate'],
        'company': json['company'] == null ? undefined : json['company'],
        'lines': json['lines'] == null ? undefined : ((json['lines'] as Array<any>).map(VendorCreditLineFromJSON)),
        'trackingCategories': json['trackingCategories'] == null ? undefined : json['trackingCategories'],
        'remoteWasDeleted': json['remoteWasDeleted'] == null ? undefined : json['remoteWasDeleted'],
        'accountingPeriod': json['accountingPeriod'] == null ? undefined : json['accountingPeriod'],
        'modifiedAt': json['modifiedAt'] == null ? undefined : (new Date(json['modifiedAt'])),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function VendorCreditToJSON(value?: VendorCredit | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'mergeRecordId': value['mergeRecordId'],
        'remoteId': value['remoteId'],
        'number': value['number'],
        'transactionDate': value['transactionDate'] == null ? undefined : ((value['transactionDate']).toISOString()),
        'vendor': value['vendor'],
        'totalAmount': value['totalAmount'],
        'currency': value['currency'],
        'exchangeRate': value['exchangeRate'],
        'company': value['company'],
        'lines': value['lines'] == null ? undefined : ((value['lines'] as Array<any>).map(VendorCreditLineToJSON)),
        'trackingCategories': value['trackingCategories'],
        'remoteWasDeleted': value['remoteWasDeleted'],
        'accountingPeriod': value['accountingPeriod'],
        'modifiedAt': value['modifiedAt'] == null ? undefined : ((value['modifiedAt']).toISOString()),
        'id': value['id'],
    };
}

