apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      nodePort: {{ .Values.service.nodeport }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics.port }}
      targetPort: http
      protocol: TCP
      name: metrics
      nodePort: {{ .Values.service.metrics.nodeport }}
  selector:
    {{- include "api-gateway.selectorLabels" . | nindent 4 }}
